@extends('layouts.app')
@section('title', 'Audit Log')
@section('header', 'Security & Audit Trail')
@section('subheader', 'Tamper-evident chronological record of user actions, security events, and inventory changes')

@section('header-actions')
    <a href="{{ request()->fullUrlWithQuery(['export' => 'excel']) }}" class="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-bold text-emerald-800 bg-emerald-50 border border-emerald-200 hover:bg-emerald-100 shadow-xs transition-all print:hidden">
        <svg class="w-4 h-4 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
        Export Excel
    </a>
    <a href="{{ request()->fullUrlWithQuery(['print' => 'all']) }}" target="_blank" class="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-bold text-gray-700 bg-white border border-gray-200 hover:bg-gray-50 shadow-xs transition-all print:hidden">
        <svg class="w-4 h-4 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"/></svg>
        Print Report
    </a>
    <a href="{{ route('users.index') }}" class="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-semibold text-gray-700 bg-white border border-gray-200 hover:bg-gray-50 shadow-xs transition-all print:hidden">
        <svg class="w-4 h-4 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z"/></svg>
        Manage Users
    </a>
@endsection

@section('content')
{{-- Print-only header --}}
<div class="hidden print:block mb-6 pb-4 border-b border-gray-300">
    <div class="flex items-center justify-between">
        <div>
            <h1 class="text-xl font-black text-gray-900 tracking-tight">HEIM COFFEE SHOP</h1>
            <p class="text-sm font-bold text-gray-700 mt-0.5">Security & Audit Trail Report</p>
        </div>
        <div class="text-right text-xs text-gray-500">
            <p>Printed: <span class="font-semibold text-gray-800">{{ now(config('app.business_timezone', 'Asia/Manila'))->format('M d, Y h:i A') }}</span></p>
            <p>Generated by: <span class="font-semibold text-gray-800">{{ auth()->user()->name }} ({{ ucfirst(auth()->user()->role) }})</span></p>
            @if(request('from') || request('to'))
                <p>Period: <span class="font-semibold text-gray-800">{{ request('from', 'Start') }} to {{ request('to', 'Present') }}</span></p>
            @endif
        </div>
    </div>
</div>

{{-- Filter toolbar --}}
<div class="brand-card rounded-2xl p-4 mb-6 shadow-sm print:hidden">
    <form method="GET" class="flex flex-col sm:flex-row sm:items-end gap-3 flex-wrap">
        <div class="flex-1 min-w-[200px]">
            <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Search Events</label>
            <div class="relative">
                <span class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-gray-400">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/></svg>
                </span>
                <input type="text" name="search" value="{{ request('search') }}" placeholder="Search actor, action, or module..."
                    class="w-full pl-9 pr-3 py-2 bg-gray-50 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all">
            </div>
        </div>

        <div class="w-36">
            <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Module</label>
            <select name="module" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all">
                <option value="">All Modules</option>
                @foreach($modules as $m)
                <option value="{{ $m }}" {{ request('module') === $m ? 'selected' : '' }}>{{ $m }}</option>
                @endforeach
            </select>
        </div>

        <div class="w-36">
            <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Staff Role</label>
            <select name="actor_role" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all">
                <option value="">All Roles</option>
                @foreach($roles as $r)
                <option value="{{ $r }}" {{ request('actor_role') === $r ? 'selected' : '' }}>{{ ucfirst($r) }}</option>
                @endforeach
            </select>
        </div>

        <div>
            <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">From Date</label>
            <input type="date" name="from" value="{{ request('from') }}"
                class="bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all">
        </div>

        <div>
            <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">To Date</label>
            <input type="date" name="to" value="{{ request('to') }}"
                class="bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all">
        </div>

        <div class="flex items-center gap-2">
            <button type="submit" class="brand-btn-filter">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 4a1 1 0 011-1h16a1 1 0 011 1v2.586a1 1 0 01-.293.707l-6.414 6.414a1 1 0 00-.293.707V17l-4 4v-6.586a1 1 0 00-.293-.707L3.293 7.293A1 1 0 013 6.586V4z"/></svg>
                Filter
            </button>
            @if(request('search') || request('module') || request('actor_role') || request('from') || request('to'))
            <a href="{{ route('audit-logs.index') }}" class="brand-btn-reset">
                Clear
            </a>
            @endif
        </div>
    </form>
</div>

{{-- Audit Table --}}
<div class="brand-card rounded-2xl overflow-hidden">
    <div class="flex items-center justify-between px-6 py-4 border-b border-gray-100">
        <div>
            <h2 class="font-bold text-gray-900 text-base">Recorded Activities</h2>
            <p class="text-xs text-gray-400">Chronological ledger of security and data mutations</p>
        </div>
        <span class="text-xs font-semibold px-2.5 py-1 rounded-full bg-gray-100 text-gray-600">
            {{ $logs instanceof \Illuminate\Pagination\LengthAwarePaginator ? $logs->total() : $logs->count() }} entries
        </span>
    </div>

    <div class="overflow-x-auto">
        <table class="w-full text-sm">
            <thead class="bg-gray-50/75 border-b border-gray-100 text-xs font-bold text-gray-500 uppercase tracking-wider">
                <tr>
                    <th class="px-5 py-3.5 text-left">Timestamp</th>
                    <th class="px-5 py-3.5 text-left">Actor</th>
                    <th class="px-5 py-3.5 text-left">Role</th>
                    <th class="px-5 py-3.5 text-left">Action</th>
                    <th class="px-5 py-3.5 text-left">Module</th>
                    <th class="px-5 py-3.5 text-left">IP Address</th>
                    <th class="px-5 py-3.5 text-left">Reason / Context</th>
                </tr>
            </thead>
            <tbody class="divide-y divide-gray-100">
                @forelse($logs as $log)
                <tr class="hover:bg-gray-50/60 transition-colors">
                    <td class="px-5 py-3.5 text-xs text-gray-500 whitespace-nowrap font-mono">
                        {{ $log->created_at->copy()->timezone(config('app.business_timezone', 'Asia/Manila'))->format('M d, Y H:i:s') }}
                    </td>
                    <td class="px-5 py-3.5 font-semibold text-gray-900 whitespace-nowrap">
                        {{ $log->actor_name ?? 'System' }}
                    </td>
                    <td class="px-5 py-3.5 whitespace-nowrap">
                        <span class="inline-flex items-center px-2 py-0.5 rounded text-[11px] font-bold uppercase tracking-wider
                            {{ $log->actor_role === 'owner' ? 'bg-amber-100 text-amber-800' :
                               ($log->actor_role === 'manager' ? 'bg-heim-100 text-heim-800' : 'bg-gray-100 text-gray-700') }}">
                            {{ $log->actor_role }}
                        </span>
                    </td>
                    <td class="px-5 py-3.5 font-mono text-xs text-gray-700 whitespace-nowrap">
                        <span class="font-semibold text-heim-800">{{ $log->action }}</span>
                    </td>
                    <td class="px-5 py-3.5 text-xs text-gray-600 whitespace-nowrap">
                        {{ $log->module }}
                    </td>
                    <td class="px-5 py-3.5 text-xs text-gray-400 font-mono whitespace-nowrap">
                        {{ $log->ip_address ?? '—' }}
                    </td>
                    <td class="px-5 py-3.5 text-xs text-gray-600 max-w-xs truncate">
                        {{ $log->reason ?? '—' }}
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="7" class="px-5 py-12 text-center">
                        <div class="flex flex-col items-center justify-center">
                            <div class="w-12 h-12 rounded-2xl bg-gray-50 flex items-center justify-center text-gray-300 mb-2">
                                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
                            </div>
                            <p class="text-sm font-semibold text-gray-700">No audit log entries found</p>
                            <p class="text-xs text-gray-400">Try broadening your search or clear filters.</p>
                        </div>
                    </td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    @if($logs instanceof \Illuminate\Pagination\LengthAwarePaginator && $logs->hasPages())
    <div class="px-6 py-4 border-t border-gray-100 bg-gray-50/50 print:hidden">
        {{ $logs->links() }}
    </div>
    @endif
</div>
@endsection
