@extends('layouts.app')
@section('title', 'Stock Movements')
@section('header', 'Stock Movements')
@section('subheader', 'Review every delivery, sale, waste entry, and inventory adjustment in one ledger')

@section('header-actions')
    <div class="flex items-center gap-2">
    @if(auth()->user()->canExportOrPrint())
        <a href="{{ request()->fullUrlWithQuery(['export' => 'excel']) }}" class="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-bold text-emerald-800 bg-emerald-50 border border-emerald-200 hover:bg-emerald-100 shadow-xs transition-all print:hidden">
            <svg class="w-4 h-4 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
            Export Excel
        </a>
        <a href="{{ request()->fullUrlWithQuery(['print' => 'all']) }}" target="_blank" class="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-bold text-gray-700 bg-white border border-gray-200 hover:bg-gray-50 shadow-xs transition-all print:hidden">
            <svg class="w-4 h-4 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"/></svg>
            Print Report
        </a>
    @endif
    </div>
@endsection

@section('content')
{{-- Print-only header --}}
<div class="hidden print:block mb-6 pb-4 border-b border-gray-300">
    <div class="flex items-center justify-between">
        <div>
            <h1 class="text-xl font-black text-gray-900 tracking-tight">HEIM COFFEE SHOP</h1>
            <p class="text-sm font-bold text-gray-700 mt-0.5">
                @php $activeType = $reportType ?? request('type'); @endphp
                @if($activeType === 'stock_in')
                    Stock-In Delivery & Shipment Report
                @elseif($activeType === 'waste')
                    Waste & Spoilage Incident Report
                @else
                    Stock Adjustments & Movements Report
                @endif
            </p>
        </div>
        <div class="text-right text-xs text-gray-500">
            <p>Printed: <span class="font-semibold text-gray-800">{{ now()->format('M d, Y h:i A') }}</span></p>
            <p>Generated by: <span class="font-semibold text-gray-800">{{ auth()->user()->name }} ({{ ucfirst(auth()->user()->role) }})</span></p>
            @if(request('from') || request('to'))
                <p>Period: <span class="font-semibold text-gray-800">{{ request('from', 'Start') }} to {{ request('to', 'Present') }}</span></p>
            @endif
        </div>
    </div>
</div>

{{-- Movement summary --}}
<div class="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6">
    <div class="brand-card rounded-2xl p-5 shadow-sm">
        <p class="text-xs font-bold uppercase tracking-wider text-gray-400">Filtered Records</p>
        <p class="mt-1 text-2xl font-black text-gray-900">{{ number_format($summary['records']) }}</p>
    </div>
    <div class="brand-card rounded-2xl p-5 shadow-sm">
        <p class="text-xs font-bold uppercase tracking-wider text-emerald-700">Stock Added / Returned</p>
        @forelse($summary['additions'] as $movement)
            <p class="mt-1 text-xl font-black text-emerald-700">+{{ number_format($movement->total, 2) }} <span class="text-sm font-semibold">{{ $movement->unit }}</span></p>
        @empty
            <p class="mt-1 text-xl font-black text-emerald-700">0</p>
        @endforelse
    </div>
    <div class="brand-card rounded-2xl p-5 shadow-sm">
        <p class="text-xs font-bold uppercase tracking-wider text-rose-700">Stock Out</p>
        @forelse($summary['deductions'] as $movement)
            <p class="mt-1 text-xl font-black text-rose-700">−{{ number_format($movement->total, 2) }} <span class="text-sm font-semibold">{{ $movement->unit }}</span></p>
        @empty
            <p class="mt-1 text-xl font-black text-rose-700">0</p>
        @endforelse
    </div>
</div>

<div class="grid grid-cols-1 lg:grid-cols-12 gap-6">

    {{-- Form column --}}
    <div class="lg:col-span-4 print:hidden">
        <div class="brand-card rounded-2xl shadow-sm p-6 sticky top-24" x-data="{ type: '{{ old('type', in_array(request('type'), ['stock_in', 'adjustment_add', 'adjustment_deduct', 'waste'], true) ? request('type') : 'adjustment_add') }}' }">
            <div class="flex items-center gap-3 pb-4 mb-5 border-b border-gray-100">
                <div class="w-10 h-10 rounded-xl bg-heim-50 border border-heim-100 flex items-center justify-center text-heim-600">
                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4"/></svg>
                </div>
                <div>
                    <h2 class="font-bold text-gray-900 text-base">Record Adjustment / Entry</h2>
                    <p class="text-xs text-gray-400">Record stock-in, waste, or stock variance</p>
                </div>
            </div>

            <form method="POST" action="{{ route('adjustments.store') }}" class="space-y-4">
                @csrf
                <div>
                    <label class="brand-label mb-1.5">
                        Ingredient <span class="text-rose-500">*</span>
                    </label>
                    <select name="ingredient_id" required class="brand-input">
                        <option value="">Select ingredient...</option>
                        @foreach($ingredients as $ing)
                        <option value="{{ $ing->id }}" {{ old('ingredient_id') == $ing->id ? 'selected' : '' }}>
                            {{ $ing->name }} ({{ $ing->unit }}) — {{ number_format($ing->getCurrentStock(), 3) }} current
                        </option>
                        @endforeach
                    </select>
                </div>

                <div>
                    <label class="brand-label mb-1.5">
                        Adjustment Direction / Type <span class="text-rose-500">*</span>
                    </label>
                    <div class="grid grid-cols-2 gap-2">
                        <label class="flex items-center justify-center gap-1.5 p-2.5 border-2 border-gray-200 rounded-xl cursor-pointer hover:border-emerald-400 has-[:checked]:border-emerald-600 has-[:checked]:bg-emerald-50/80 transition-all">
                            <input type="radio" name="type" value="stock_in" x-model="type" class="text-emerald-600 focus:ring-emerald-500">
                            <span class="text-xs font-bold text-emerald-800">+ Stock-In</span>
                        </label>
                        <label class="flex items-center justify-center gap-1.5 p-2.5 border-2 border-gray-200 rounded-xl cursor-pointer hover:border-heim-400 has-[:checked]:border-heim-600 has-[:checked]:bg-heim-50/80 transition-all">
                            <input type="radio" name="type" value="adjustment_add" x-model="type" class="text-heim-600 focus:ring-heim-500">
                            <span class="text-xs font-bold text-heim-800">+ Add Stock</span>
                        </label>
                        <label class="flex items-center justify-center gap-1.5 p-2.5 border-2 border-gray-200 rounded-xl cursor-pointer hover:border-amber-400 has-[:checked]:border-amber-600 has-[:checked]:bg-amber-50/80 transition-all">
                            <input type="radio" name="type" value="adjustment_deduct" x-model="type" class="text-amber-600 focus:ring-amber-500">
                            <span class="text-xs font-bold text-amber-800">− Stock-Out</span>
                        </label>
                        <label class="flex items-center justify-center gap-1.5 p-2.5 border-2 border-gray-200 rounded-xl cursor-pointer hover:border-rose-400 has-[:checked]:border-rose-600 has-[:checked]:bg-rose-50/80 transition-all">
                            <input type="radio" name="type" value="waste" x-model="type" class="text-rose-600 focus:ring-rose-500">
                            <span class="text-xs font-bold text-rose-800">− Waste / Spoilage</span>
                        </label>
                    </div>
                </div>

                <div>
                    <label class="brand-label mb-1.5">
                        Quantity <span class="text-rose-500">*</span>
                    </label>
                    <input type="number" name="quantity" value="{{ old('quantity') }}" min="0.001" step="0.001" placeholder="0.000" class="brand-input font-bold" required>
                </div>

                {{-- Conditional fields for Stock-In --}}
                <div x-show="type === 'stock_in'" x-transition class="space-y-3.5 pt-2 border-t border-gray-100">
                    <div>
                        <label class="brand-label mb-1.5">Supplier / Vendor (Optional)</label>
                        <select name="supplier_id" class="brand-input">
                            <option value="">Walk-in / Direct Purchase</option>
                            @foreach($suppliers as $supplier)
                            <option value="{{ $supplier->id }}" {{ old('supplier_id') == $supplier->id ? 'selected' : '' }}>
                                {{ $supplier->name }}
                            </option>
                            @endforeach
                        </select>
                    </div>
                    <div>
                        <label class="brand-label mb-1.5">Invoice / Ref # (Optional)</label>
                        <input type="text" name="reference_number" value="{{ old('reference_number') }}" placeholder="e.g. INV-2026-001" class="brand-input">
                    </div>
                    <div class="grid grid-cols-2 gap-3">
                        <div>
                            <label class="brand-label mb-1.5">Unit Cost (₱) <span class="text-rose-500">*</span></label>
                            <input type="number" name="unit_cost" value="{{ old('unit_cost') }}" min="0" step="0.01" class="brand-input" :required="type === 'stock_in'">
                        </div>
                        <div>
                            <label class="brand-label mb-1.5">Received Date <span class="text-rose-500">*</span></label>
                            <input type="date" name="transaction_date" value="{{ old('transaction_date', now()->toDateString()) }}" class="brand-input" :required="type === 'stock_in'">
                        </div>
                    </div>
                    <div>
                        <label class="brand-label mb-1.5">Expiration Date</label>
                        <input type="date" name="expiration_date" value="{{ old('expiration_date') }}" class="brand-input">
                    </div>
                </div>

                <div x-show="type === 'waste'">
                    <label class="brand-label mb-1.5">Stock-Out Reason <span class="text-rose-500">*</span></label>
                    <select name="waste_reason" class="brand-input" :required="type === 'waste'">
                        @foreach(['Waste', 'Spoilage', 'Expired', 'Damaged', 'Adjustment', 'Other'] as $reasonOption)
                        <option value="{{ $reasonOption }}" @selected(old('waste_reason') === $reasonOption)>{{ $reasonOption }}</option>
                        @endforeach
                    </select>
                </div>

                <div x-show="type !== 'waste'">
                    <label class="brand-label mb-1.5">
                        Reason <span class="text-rose-500" x-show="type === 'adjustment_add' || type === 'adjustment_deduct'">*</span>
                    </label>
                    <textarea name="reason" rows="3"
                        placeholder="Explain the stock adjustment or add any delivery details..."
                        class="brand-input" :required="type === 'adjustment_add' || type === 'adjustment_deduct'">{{ old('reason') }}</textarea>
                </div>
                <div>
                    <label class="brand-label mb-1.5">Additional Notes</label>
                    <textarea name="notes" rows="2" placeholder="Optional notes" class="brand-input">{{ old('notes') }}</textarea>
                </div>

                <div class="pt-2">
                    <button type="submit" class="brand-btn-primary w-full py-2.5 text-sm font-bold shadow-md shadow-heim-600/20 active:scale-[0.98] transition-all flex items-center justify-center gap-2">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/></svg>
                        <span x-text="type === 'stock_in' ? 'Post Stock-In' : (type === 'waste' ? 'Record Waste / Spoilage' : 'Post Adjustment')">Post Adjustment</span>
                    </button>
                </div>
            </form>
        </div>
    </div>

    {{-- History column --}}
    <div class="lg:col-span-8 print:w-full print:col-span-12">
        {{-- Filter toolbar --}}
        <div class="brand-card rounded-2xl p-4 mb-5 shadow-sm print:hidden">
            <form method="GET" class="flex flex-col sm:flex-row sm:items-end gap-3 flex-wrap">
                <div class="w-full sm:w-auto flex-1 min-w-[140px]">
                    <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Type Filter</label>
                    <select name="type" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all">
                        <option value="">All Movement Types</option>
                        <option value="stock_in" {{ request('type') === 'stock_in' ? 'selected' : '' }}>Stock-In (+)</option>
                        <option value="sales_consumption" {{ request('type') === 'sales_consumption' ? 'selected' : '' }}>Consumption (-)</option>
                        <option value="sales_return" {{ request('type') === 'sales_return' ? 'selected' : '' }}>Sales Return (+)</option>
                        <option value="adjustment_add" {{ request('type') === 'adjustment_add' ? 'selected' : '' }}>Adjustment (+)</option>
                        <option value="adjustment_deduct" {{ request('type') === 'adjustment_deduct' ? 'selected' : '' }}>Stock-Out (-)</option>
                        <option value="waste" {{ request('type') === 'waste' ? 'selected' : '' }}>Waste / Spoilage (-)</option>
                    </select>
                </div>
                <div class="w-full sm:w-auto flex-1 min-w-[150px]">
                    <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Ingredient</label>
                    <select name="ingredient_id" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all">
                        <option value="">All Ingredients</option>
                        @foreach($ingredients as $ing)
                        <option value="{{ $ing->id }}" {{ request('ingredient_id') == $ing->id ? 'selected' : '' }}>{{ $ing->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="w-full sm:w-auto">
                    <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">From Date</label>
                    <input type="date" name="from" value="{{ request('from') }}" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all">
                </div>
                <div class="w-full sm:w-auto">
                    <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">To Date</label>
                    <input type="date" name="to" value="{{ request('to') }}" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all">
                </div>
                <div class="flex items-center gap-2 pt-1 sm:pt-0">
                    <button type="submit" class="brand-btn-filter">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 4a1 1 0 011-1h16a1 1 0 011 1v2.586a1 1 0 01-.293.707l-6.414 6.414a1 1 0 00-.293.707V17l-4 4v-6.586a1 1 0 00-.293-.707L3.293 7.293A1 1 0 013 6.586V4z"/></svg>
                        Filter
                    </button>
                    @if(request('type') || request('ingredient_id') || request('from') || request('to'))
                    <a href="{{ route('adjustments.index') }}" class="border border-gray-200 text-gray-600 hover:bg-gray-50 px-3.5 py-2 rounded-xl text-sm font-medium transition-colors">
                        Clear
                    </a>
                    @endif
                </div>
            </form>
        </div>

        {{-- Table container --}}
        <div class="brand-card rounded-2xl shadow-sm overflow-hidden">
            <div class="px-6 py-4 border-b border-gray-100 flex items-center justify-between">
                <div>
                    <h2 class="font-bold text-gray-900 text-base">Movement Ledger</h2>
                    <p class="text-xs text-gray-400">Combined ledger of stock in, sales consumption, stock out, waste, and adjustments</p>
                </div>
                <span class="text-xs font-semibold px-2.5 py-1 rounded-full bg-gray-100 text-gray-600">
                    {{ $transactions instanceof \Illuminate\Pagination\LengthAwarePaginator ? $transactions->total() : $transactions->count() }} records
                </span>
            </div>

            <div class="overflow-x-auto">
                <table class="w-full text-sm">
                    <thead class="bg-gray-50/75 border-b border-gray-100 text-xs font-bold text-gray-500 uppercase tracking-wider">
                        <tr>
                            <th class="px-5 py-3.5 text-left">Ingredient</th>
                            <th class="px-5 py-3.5 text-center">Type</th>
                            <th class="px-5 py-3.5 text-right">Qty</th>
                            <th class="px-5 py-3.5 text-right">Previous</th>
                            <th class="px-5 py-3.5 text-right">New Stock</th>
                            <th class="px-5 py-3.5 text-left">Context / Reason</th>
                            <th class="px-5 py-3.5 text-right">Date</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-gray-100">
                        @forelse($transactions as $tx)
                        @php 
                            $isAdd = in_array($tx->type, ['adjustment_add', 'stock_in']);
                        @endphp
                        <tr class="hover:bg-gray-50/60 transition-colors">
                            <td class="px-5 py-3.5">
                                <span class="font-bold text-gray-900">{{ $tx->ingredient?->name ?? '—' }}</span>
                                <div class="text-[11px] text-gray-400">{{ $tx->performed_by ? 'By ' . $tx->performed_by : '' }}</div>
                            </td>
                            <td class="px-5 py-3.5 text-center">
                                @if($tx->type === 'stock_in')
                                    <span class="inline-flex items-center px-2 py-0.5 rounded text-xs font-bold bg-emerald-100 text-emerald-800 border border-emerald-200">
                                        + Stock-In
                                    </span>
                                @elseif($tx->type === 'adjustment_add')
                                    <span class="inline-flex items-center px-2 py-0.5 rounded text-xs font-bold bg-teal-100 text-teal-800 border border-teal-200">
                                        + Add Stock
                                    </span>
                                @elseif($tx->type === 'adjustment_deduct')
                                    <span class="inline-flex items-center px-2 py-0.5 rounded text-xs font-bold bg-amber-100 text-amber-800 border border-amber-200">
                                        − Stock-Out
                                    </span>
                                @elseif($tx->type === 'waste')
                                    <span class="inline-flex items-center px-2 py-0.5 rounded text-xs font-bold bg-rose-100 text-rose-800 border border-rose-200">
                                        − Waste
                                    </span>
                                @elseif($tx->type === 'sales_consumption')
                                    <span class="inline-flex items-center px-2 py-0.5 rounded text-xs font-bold bg-blue-100 text-blue-800 border border-blue-200">
                                        − Sales Consumption
                                    </span>
                                @elseif($tx->type === 'sales_return')
                                    <span class="inline-flex items-center px-2 py-0.5 rounded text-xs font-bold bg-emerald-100 text-emerald-800 border border-emerald-200">
                                        + Sales Return
                                    </span>
                                @else
                                    <span class="inline-flex items-center px-2 py-0.5 rounded text-xs font-bold bg-gray-100 text-gray-800">
                                        {{ $tx->getTypeLabel() }}
                                    </span>
                                @endif
                            </td>
                            <td class="px-5 py-3.5 text-right">
                                <span class="font-bold {{ $isAdd ? 'text-emerald-700' : 'text-rose-700' }}">
                                    {{ $isAdd ? '+' : '−' }}{{ number_format($tx->quantity, 3) }}
                                    <span class="text-xs font-normal text-gray-400">{{ $tx->ingredient?->unit }}</span>
                                </span>
                            </td>
                            <td class="px-5 py-3.5 text-right text-gray-400 text-xs">{{ number_format($tx->previous_stock, 3) }}</td>
                            <td class="px-5 py-3.5 text-right font-bold text-gray-800">{{ number_format($tx->new_stock, 3) }}</td>
                            <td class="px-5 py-3.5 text-xs text-gray-600 max-w-xs truncate" title="{{ $tx->reason }}">
                                <div>{{ $tx->reason ?? '—' }}</div>
                                @if($tx->supplier)
                                    <div class="text-[11px] text-emerald-700 font-semibold mt-0.5">Vendor: {{ $tx->supplier->name }}</div>
                                @endif
                                @if($tx->unit_cost !== null)
                                    <div class="text-[11px] text-gray-500">Unit cost: ₱{{ number_format($tx->unit_cost, 2) }}</div>
                                @endif
                                @if($tx->expiration_date)
                                    <div class="text-[11px] text-amber-700">Expires: {{ $tx->expiration_date->format('M d, Y') }}</div>
                                @endif
                                @if($tx->reference_number)
                                    <div class="text-[10px] text-gray-400">Ref: {{ $tx->reference_number }}</div>
                                @endif
                            </td>
                            <td class="px-5 py-3.5 text-right text-xs text-gray-500 whitespace-nowrap">
                                <div>{{ ($tx->transaction_date ?? $tx->created_at)->format('M d, Y') }}</div>
                                <div class="text-[10px] text-gray-400">Recorded {{ $tx->created_at->format('h:i A') }}</div>
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td colspan="7" class="px-5 py-12 text-center">
                                <div class="flex flex-col items-center justify-center">
                                    <div class="w-12 h-12 rounded-2xl bg-gray-50 flex items-center justify-center text-gray-300 mb-2">
                                        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4"/></svg>
                                    </div>
                                    <p class="text-sm font-semibold text-gray-700">No stock movements found</p>
                                    <p class="text-xs text-gray-400">Recorded Stock-In, Waste, and Adjustments will appear here.</p>
                                </div>
                            </td>
                        </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>

            @if($transactions instanceof \Illuminate\Pagination\LengthAwarePaginator && $transactions->hasPages())
            <div class="px-6 py-4 border-t border-gray-100 bg-gray-50/50 print:hidden">
                {{ $transactions->links() }}
            </div>
            @endif
        </div>
    </div>
</div>
@endsection
