@extends('layouts.app')
@section('title', 'Stock Overview')
@section('header', 'Stock Overview')
@section('subheader', 'Live ingredient tracking, reorder thresholds, and consumption status')

@section('header-actions')
    <div class="flex items-center gap-2">
    @if(auth()->user()->canExportOrPrint())
        <a href="{{ request()->fullUrlWithQuery(['export' => 'excel']) }}" class="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-bold text-emerald-800 bg-emerald-50 border border-emerald-200 hover:bg-emerald-100 shadow-xs transition-all print:hidden">
            <svg class="w-4 h-4 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
            Export Excel
        </a>
        <button onclick="window.print()" class="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-bold text-gray-700 bg-white border border-gray-200 hover:bg-gray-50 shadow-xs transition-all print:hidden">
            <svg class="w-4 h-4 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"/></svg>
            Print Report
        </button>
    @endif
        <a href="{{ route('adjustments.index', ['type' => 'stock_in']) }}" class="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-bold text-white bg-heim-600 hover:bg-heim-700 shadow-md shadow-heim-600/20 active:scale-95 transition-all print:hidden">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg>
            Record Stock-In
        </a>
    </div>
@endsection

@section('content')
{{-- Print-only header --}}
<div class="hidden print:block mb-6 pb-4 border-b border-gray-300">
    <div class="flex items-center justify-between">
        <div>
            <h1 class="text-xl font-black text-gray-900 tracking-tight">HEIM COFFEE SHOP</h1>
            <p class="text-sm font-bold text-gray-700 mt-0.5">Stock Overview & Inventory Status Report</p>
        </div>
        <div class="text-right text-xs text-gray-500">
            <p>Printed: <span class="font-semibold text-gray-800">{{ now(config('app.business_timezone', 'Asia/Manila'))->format('M d, Y h:i A') }}</span></p>
            <p>Generated by: <span class="font-semibold text-gray-800">{{ auth()->user()->name }} ({{ ucfirst(auth()->user()->role) }})</span></p>
            @if(request('stock_status'))
                <p>Status Filter: <span class="font-semibold text-gray-800">{{ ucwords(str_replace('_', ' ', request('stock_status'))) }}</span></p>
            @endif
        </div>
    </div>
</div>

{{-- Summary cards --}}
<div class="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6">
    <div class="bg-white rounded-2xl p-5 border border-heim-100 shadow-sm relative overflow-hidden group hover:shadow-md transition-all">
        <div class="flex items-center justify-between">
            <div>
                <p class="text-xs font-bold text-heim-600 uppercase tracking-wider mb-1">Good Stock</p>
                <div class="flex items-baseline gap-2">
                    <span class="text-3xl font-black text-heim-800">{{ $good }}</span>
                    <span class="text-xs text-gray-500 font-medium">healthy items</span>
                </div>
            </div>
            <div class="w-12 h-12 rounded-2xl bg-heim-50 border border-heim-100 flex items-center justify-center text-heim-600 group-hover:scale-110 transition-transform">
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
            </div>
        </div>
        <div class="mt-3 w-full bg-heim-50 rounded-full h-1.5 overflow-hidden">
            @php $totalCount = max(1, $good + $low + $outOfStock); @endphp
            <div class="bg-heim-500 h-1.5 rounded-full" style="width: {{ round(($good / $totalCount) * 100) }}%"></div>
        </div>
    </div>

    <div class="bg-white rounded-2xl p-5 border {{ $low > 0 ? 'border-amber-200 bg-amber-50/30' : 'border-gray-100' }} shadow-sm relative overflow-hidden group hover:shadow-md transition-all">
        <div class="flex items-center justify-between">
            <div>
                <p class="text-xs font-bold {{ $low > 0 ? 'text-amber-600' : 'text-gray-500' }} uppercase tracking-wider mb-1">Low Stock Warning</p>
                <div class="flex items-baseline gap-2">
                    <span class="text-3xl font-black {{ $low > 0 ? 'text-amber-700' : 'text-gray-800' }}">{{ $low }}</span>
                    <span class="text-xs text-gray-500 font-medium">needs reorder</span>
                </div>
            </div>
            <div class="w-12 h-12 rounded-2xl {{ $low > 0 ? 'bg-amber-100/70 text-amber-700 border border-amber-200' : 'bg-gray-50 text-gray-400 border border-gray-100' }} flex items-center justify-center group-hover:scale-110 transition-transform">
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"/></svg>
            </div>
        </div>
        <div class="mt-3 w-full bg-gray-100 rounded-full h-1.5 overflow-hidden">
            <div class="bg-amber-500 h-1.5 rounded-full" style="width: {{ round(($low / $totalCount) * 100) }}%"></div>
        </div>
    </div>

    <div class="bg-white rounded-2xl p-5 border {{ $outOfStock > 0 ? 'border-red-200 bg-red-50/30' : 'border-gray-100' }} shadow-sm relative overflow-hidden group hover:shadow-md transition-all">
        <div class="flex items-center justify-between">
            <div>
                <p class="text-xs font-bold {{ $outOfStock > 0 ? 'text-red-600' : 'text-gray-500' }} uppercase tracking-wider mb-1">Out of Stock</p>
                <div class="flex items-baseline gap-2">
                    <span class="text-3xl font-black {{ $outOfStock > 0 ? 'text-red-700' : 'text-gray-800' }}">{{ $outOfStock }}</span>
                    <span class="text-xs text-gray-500 font-medium">depleted</span>
                </div>
            </div>
            <div class="w-12 h-12 rounded-2xl {{ $outOfStock > 0 ? 'bg-red-100/80 text-red-700 border border-red-200' : 'bg-gray-50 text-gray-400 border border-gray-100' }} flex items-center justify-center group-hover:scale-110 transition-transform">
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636"/></svg>
            </div>
        </div>
        <div class="mt-3 w-full bg-gray-100 rounded-full h-1.5 overflow-hidden">
            <div class="bg-red-500 h-1.5 rounded-full" style="width: {{ round(($outOfStock / $totalCount) * 100) }}%"></div>
        </div>
    </div>
</div>

{{-- Filter toolbar --}}
<div class="bg-white rounded-2xl shadow-sm border border-gray-100 p-4 mb-6 print:hidden">
    <form method="GET" class="flex flex-col md:flex-row md:items-center justify-between gap-3">
        <div class="flex flex-1 flex-wrap items-center gap-3">
            <div class="relative flex-1 min-w-[200px]">
                <span class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-gray-400">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/></svg>
                </span>
                <input type="text" name="search" value="{{ request('search') }}" placeholder="Search ingredient name..."
                    class="w-full pl-9 pr-3 py-2 bg-gray-50 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all">
            </div>

            <div class="w-44">
                <select name="stock_status" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all">
                    <option value="">All Stock Statuses</option>
                    <option value="good" {{ $stockFilter === 'good' ? 'selected' : '' }}>Good Stock</option>
                    <option value="low_stock" {{ $stockFilter === 'low_stock' ? 'selected' : '' }}>Low Stock</option>
                    <option value="out_of_stock" {{ $stockFilter === 'out_of_stock' ? 'selected' : '' }}>Out of Stock</option>
                </select>
            </div>

            <button type="submit" class="brand-btn-filter">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 4a1 1 0 011-1h16a1 1 0 011 1v2.586a1 1 0 01-.293.707l-6.414 6.414a1 1 0 00-.293.707V17l-4 4v-6.586a1 1 0 00-.293-.707L3.293 7.293A1 1 0 013 6.586V4z"/></svg>
                Filter
            </button>

            @if(request('search') || request('stock_status'))
            <a href="{{ route('inventory.index') }}" class="brand-btn-reset">
                Clear
            </a>
            @endif
        </div>

        <div class="text-xs font-semibold text-gray-500 self-end md:self-center">
            Total: <span class="text-gray-900 font-bold">{{ $ingredients->count() }}</span> ingredients
        </div>
    </form>
</div>

{{-- Stock table --}}
<div class="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
    <div class="overflow-x-auto">
        <table class="w-full text-sm">
            <thead class="bg-gray-50/75 border-b border-gray-100 text-xs font-bold text-gray-500 uppercase tracking-wider">
                <tr>
                    <th class="px-5 py-4 text-left">Ingredient</th>
                    <th class="px-5 py-4 text-right">Current Stock</th>
                    <th class="px-5 py-4 text-right">Min Threshold</th>
                    <th class="px-5 py-4 text-right">Reorder Level</th>
                    <th class="px-5 py-4 text-left min-w-[140px]">Capacity Status</th>
                    <th class="px-5 py-4 text-center">Health</th>
                    <th class="px-5 py-4 text-right print:hidden">Action</th>
                </tr>
            </thead>
            <tbody class="divide-y divide-gray-100">
                @forelse($ingredients as $ingredient)
                @php
                    $current = $ingredient->getCurrentStock();
                    $min     = (float) $ingredient->minimum_stock;
                    $reorder = (float) ($ingredient->reorder_level ?: $min);
                    $ss      = $ingredient->getStockStatus();
                    $ratio   = $reorder > 0 ? min(100, round(($current / $reorder) * 100)) : 100;
                @endphp
                <tr class="hover:bg-gray-50/60 transition-colors {{ $ss === 'out_of_stock' ? 'bg-red-50/20' : ($ss === 'low_stock' ? 'bg-amber-50/20' : '') }}">
                    <td class="px-5 py-4">
                        <div class="font-bold text-gray-900">{{ $ingredient->name }}</div>
                        <div class="text-xs text-gray-400">Unit: {{ $ingredient->unit }} · #{{ str_pad($ingredient->id, 4, '0', STR_PAD_LEFT) }}</div>
                        <div class="text-[11px] text-gray-500">Cost: ₱{{ number_format($ingredient->cost, 2) }} · Supplier: {{ $ingredient->supplier?->name ?? '—' }}</div>
                        <div class="text-[11px] text-gray-500">Expires: {{ $ingredient->expiration_date?->format('M d, Y') ?? '—' }}</div>
                    </td>
                    <td class="px-5 py-4 text-right">
                        <span class="font-extrabold text-base {{ $ss === 'out_of_stock' ? 'text-red-600' : ($ss === 'low_stock' ? 'text-amber-600' : 'text-heim-700') }}">
                            {{ number_format($current, 3) }}
                        </span>
                        <span class="text-xs text-gray-400 ml-0.5">{{ $ingredient->unit }}</span>
                    </td>
                    <td class="px-5 py-4 text-right text-gray-500 font-medium">
                        {{ number_format($min, 3) }}
                        <span class="text-xs text-gray-400 ml-0.5">{{ $ingredient->unit }}</span>
                    </td>
                    <td class="px-5 py-4 text-right text-gray-500 font-medium">
                        {{ number_format($reorder, 3) }}
                        <span class="text-xs text-gray-400 ml-0.5">{{ $ingredient->unit }}</span>
                    </td>
                    <td class="px-5 py-4">
                        <div class="w-full">
                            <div class="flex justify-between text-[11px] font-semibold mb-1 {{ $ss === 'out_of_stock' ? 'text-red-600' : ($ss === 'low_stock' ? 'text-amber-600' : 'text-heim-600') }}">
                                <span>{{ $ss === 'out_of_stock' ? 'Depleted' : ($ss === 'low_stock' ? 'Low' : 'Adequate') }}</span>
                                <span>{{ $reorder > 0 ? $ratio . '%' : 'N/A' }}</span>
                            </div>
                            <div class="w-full bg-gray-100 rounded-full h-2 overflow-hidden">
                                <div class="h-2 rounded-full transition-all duration-500 {{ $ss === 'out_of_stock' ? 'bg-red-500' : ($ss === 'low_stock' ? 'bg-amber-500' : 'bg-heim-500') }}"
                                     style="width: {{ $ratio }}%"></div>
                            </div>
                        </div>
                    </td>
                    <td class="px-5 py-4 text-center">
                        @include('components.status-badge', ['status' => $ss])
                    </td>
                    <td class="px-5 py-4 text-right print:hidden">
                        <div class="flex items-center justify-end gap-1.5">
                            <a href="{{ route('adjustments.index', ['ingredient_id' => $ingredient->id, 'type' => 'stock_in']) }}"
                               class="inline-flex items-center gap-1 text-xs font-bold text-emerald-800 bg-emerald-50 hover:bg-emerald-100 border border-emerald-200 px-2.5 py-1.5 rounded-lg transition-colors" title="Record Stock-In">
                                <svg class="w-3 h-3 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M12 4v16m8-8H4"/></svg>
                                Stock-In
                            </a>
                            <a href="{{ route('adjustments.index', ['ingredient_id' => $ingredient->id]) }}"
                               class="inline-flex items-center gap-1 text-xs font-bold text-heim-700 bg-heim-50 hover:bg-heim-100 border border-heim-200 px-2.5 py-1.5 rounded-lg transition-colors" title="Adjust Stock">
                                <svg class="w-3 h-3 text-heim-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4"/></svg>
                                Adjust
                            </a>
                        </div>
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="7" class="px-5 py-12 text-center">
                        <div class="flex flex-col items-center justify-center">
                            <div class="w-14 h-14 rounded-2xl bg-gray-50 flex items-center justify-center text-gray-300 mb-3">
                                <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"/></svg>
                            </div>
                            <p class="text-sm font-semibold text-gray-700 mb-1">No ingredients found</p>
                            <p class="text-xs text-gray-400 mb-4">Try adjusting your search criteria or clear your current filters.</p>
                            @if(request('search') || request('stock_status'))
                            <a href="{{ route('inventory.index') }}" class="text-xs font-bold text-heim-600 hover:text-heim-700 underline">Reset all filters</a>
                            @endif
                        </div>
                    </td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>
</div>
@endsection
