@extends('layouts.app')
@section('title', 'Stock-In Delivery')
@section('header', 'Stock-In Delivery')
@section('subheader', 'Log incoming supplier shipments, purchase deliveries, and replenish inventory')

@section('header-actions')
    <div class="flex items-center gap-2">
    @if(auth()->user()->canExportOrPrint())
        <a href="{{ request()->fullUrlWithQuery(['export' => 'excel']) }}" class="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-bold text-emerald-800 bg-emerald-50 border border-emerald-200 hover:bg-emerald-100 shadow-xs transition-all print:hidden">
            <svg class="w-4 h-4 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
            Export Excel
        </a>
        <a href="{{ request()->fullUrlWithQuery(['print' => 'all']) }}" target="_blank" class="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-bold text-gray-700 bg-white border border-gray-200 hover:bg-gray-50 shadow-xs transition-all print:hidden">
            <svg class="w-4 h-4 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"/></svg>
            Print Report
        </a>
    @endif
        <a href="{{ route('inventory.index') }}" class="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-semibold text-gray-700 bg-white border border-gray-200 hover:bg-gray-50 shadow-sm transition-all print:hidden">
            <svg class="w-4 h-4 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"/></svg>
            Back to Stock Overview
        </a>
    </div>
@endsection

@section('content')
{{-- Print-only header --}}
<div class="hidden print:block mb-6 pb-4 border-b border-gray-300">
    <div class="flex items-center justify-between">
        <div>
            <h1 class="text-xl font-black text-gray-900 tracking-tight">HEIM COFFEE SHOP</h1>
            <p class="text-sm font-bold text-gray-700 mt-0.5">Stock-In Deliveries & Shipments Report</p>
        </div>
        <div class="text-right text-xs text-gray-500">
            <p>Printed: <span class="font-semibold text-gray-800">{{ now()->format('M d, Y h:i A') }}</span></p>
            <p>Generated by: <span class="font-semibold text-gray-800">{{ auth()->user()->name }} ({{ ucfirst(auth()->user()->role) }})</span></p>
            @if(request('from') || request('to'))
                <p>Period: <span class="font-semibold text-gray-800">{{ request('from', 'Start') }} to {{ request('to', 'Present') }}</span></p>
            @endif
        </div>
    </div>
</div>

<div class="grid grid-cols-1 lg:grid-cols-12 gap-6">

    {{-- Record form --}}
    <div class="lg:col-span-4 print:hidden">
        <div class="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 sticky top-24">
            <div class="flex items-center gap-3 pb-4 mb-5 border-b border-gray-100">
                <div class="w-10 h-10 rounded-xl bg-heim-50 border border-heim-100 flex items-center justify-center text-heim-600">
                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"/></svg>
                </div>
                <div>
                    <h2 class="font-bold text-gray-900 text-base">Record Delivery</h2>
                    <p class="text-xs text-gray-400">Post shipment into active inventory</p>
                </div>
            </div>

            <form method="POST" action="{{ route('stock-in.store') }}" class="space-y-4">
                @csrf
                <div>
                    <label class="block text-xs font-bold text-gray-700 uppercase tracking-wider mb-1.5">
                        Ingredient <span class="text-red-500">*</span>
                    </label>
                    <select name="ingredient_id" required class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3.5 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all">
                        <option value="">Select ingredient...</option>
                        @foreach($ingredients as $ing)
                        <option value="{{ $ing->id }}" {{ (old('ingredient_id') == $ing->id || request('ingredient_id') == $ing->id) ? 'selected' : '' }}>
                            {{ $ing->name }} ({{ $ing->unit }}) — {{ number_format($ing->getCurrentStock(), 3) }} current
                        </option>
                        @endforeach
                    </select>
                </div>

                <div>
                    <label class="block text-xs font-bold text-gray-700 uppercase tracking-wider mb-1.5">
                        Quantity Added <span class="text-red-500">*</span>
                    </label>
                    <div class="relative">
                        <input type="number" name="quantity" value="{{ old('quantity') }}" min="0.001" step="0.001" placeholder="0.00"
                            class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3.5 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white font-semibold transition-all" required>
                    </div>
                </div>

                <div>
                    <label class="block text-xs font-bold text-gray-700 uppercase tracking-wider mb-1.5">
                        Supplier / Vendor
                    </label>
                    <select name="supplier_id" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3.5 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all">
                        <option value="">None / Walk-in Purchase</option>
                        @foreach($suppliers as $supplier)
                        <option value="{{ $supplier->id }}" {{ old('supplier_id') == $supplier->id ? 'selected' : '' }}>
                            {{ $supplier->name }}
                        </option>
                        @endforeach
                    </select>
                </div>

                <div>
                    <label class="block text-xs font-bold text-gray-700 uppercase tracking-wider mb-1.5">
                        Invoice / Reference Number
                    </label>
                    <input type="text" name="reference_number" value="{{ old('reference_number') }}" placeholder="e.g. INV-2024-001"
                        class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3.5 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all">
                </div>

                <div>
                    <label class="block text-xs font-bold text-gray-700 uppercase tracking-wider mb-1.5">
                        Delivery Notes / Purpose
                    </label>
                    <input type="text" name="reason" value="{{ old('reason') }}" placeholder="e.g. Regular weekly restock"
                        class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3.5 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all">
                </div>

                <div class="pt-2">
                    <button type="submit" class="brand-button w-full justify-center gap-2">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg>
                        Post Stock-In
                    </button>
                </div>
            </form>
        </div>
    </div>

    {{-- History column --}}
    <div class="lg:col-span-8 print:w-full print:col-span-12">
        {{-- History filter toolbar --}}
        <div class="bg-white rounded-2xl shadow-sm border border-gray-100 p-4 mb-5 print:hidden">
            <form method="GET" class="flex flex-col sm:flex-row sm:items-end gap-3">
                <div class="flex-1 min-w-[160px]">
                    <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Filter Ingredient</label>
                    <select name="ingredient_id" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all">
                        <option value="">All Ingredients</option>
                        @foreach($ingredients as $ing)
                        <option value="{{ $ing->id }}" {{ request('ingredient_id') == $ing->id ? 'selected' : '' }}>{{ $ing->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div>
                    <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">From Date</label>
                    <input type="date" name="from" value="{{ request('from') }}" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all">
                </div>
                <div>
                    <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">To Date</label>
                    <input type="date" name="to" value="{{ request('to') }}" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all">
                </div>
                <div class="flex items-center gap-2">
                    <button type="submit" class="brand-btn-filter">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 4a1 1 0 011-1h16a1 1 0 011 1v2.586a1 1 0 01-.293.707l-6.414 6.414a1 1 0 00-.293.707V17l-4 4v-6.586a1 1 0 00-.293-.707L3.293 7.293A1 1 0 013 6.586V4z"/></svg>
                        Filter
                    </button>
                    @if(request('ingredient_id') || request('from') || request('to'))
                    <a href="{{ route('stock-in.index') }}" class="brand-btn-reset">
                        Clear
                    </a>
                    @endif
                </div>
            </form>
        </div>

        {{-- Table container --}}
        <div class="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
            <div class="px-6 py-4 border-b border-gray-100 flex items-center justify-between">
                <div>
                    <h2 class="font-bold text-gray-900 text-base">Delivery History</h2>
                    <p class="text-xs text-gray-400">Chronological ledger of stock receipts</p>
                </div>
                <span class="text-xs font-semibold px-2.5 py-1 rounded-full bg-gray-100 text-gray-600">
                    {{ $transactions instanceof \Illuminate\Pagination\LengthAwarePaginator ? $transactions->total() : $transactions->count() }} records
                </span>
            </div>

            <div class="overflow-x-auto">
                <table class="w-full text-sm">
                    <thead class="bg-gray-50/75 border-b border-gray-100 text-xs font-bold text-gray-500 uppercase tracking-wider">
                        <tr>
                            <th class="px-5 py-3.5 text-left">Ingredient</th>
                            <th class="px-5 py-3.5 text-right">Qty Added</th>
                            <th class="px-5 py-3.5 text-right">Resulting Stock</th>
                            <th class="px-5 py-3.5 text-left">Supplier / Invoice</th>
                            <th class="px-5 py-3.5 text-left">Received By</th>
                            <th class="px-5 py-3.5 text-right">Date</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-gray-100">
                        @forelse($transactions as $tx)
                        <tr class="hover:bg-gray-50/60 transition-colors">
                            <td class="px-5 py-3.5">
                                <span class="font-bold text-gray-900">{{ $tx->ingredient?->name ?? '—' }}</span>
                                <div class="text-[11px] text-gray-400">{{ $tx->reason }}</div>
                            </td>
                            <td class="px-5 py-3.5 text-right">
                                <span class="font-bold text-heim-700 bg-heim-50 px-2 py-0.5 rounded-md">
                                    +{{ number_format($tx->quantity, 3) }} {{ $tx->ingredient?->unit }}
                                </span>
                            </td>
                            <td class="px-5 py-3.5 text-right font-medium text-gray-600">
                                {{ number_format($tx->new_stock, 3) }}
                            </td>
                            <td class="px-5 py-3.5 text-xs text-gray-500">
                                <div class="font-medium text-gray-800">{{ $tx->supplier->name ?? 'Direct Purchase' }}</div>
                                @if($tx->reference_number)
                                <div class="text-[11px] text-gray-400 font-mono">Ref: {{ $tx->reference_number }}</div>
                                @endif
                            </td>
                            <td class="px-5 py-3.5 text-xs text-gray-600">
                                {{ $tx->performed_by ?? 'System' }}
                            </td>
                            <td class="px-5 py-3.5 text-right text-xs text-gray-500 whitespace-nowrap">
                                <div class="text-xs font-medium text-gray-700">{{ $tx->created_at->format('M d, Y') }}</div>
                                <div class="text-[11px] text-gray-400">{{ $tx->created_at->format('h:i A') }}</div>
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td colspan="6" class="px-5 py-12 text-center">
                                <div class="flex flex-col items-center justify-center">
                                    <div class="w-12 h-12 rounded-2xl bg-gray-50 flex items-center justify-center text-gray-300 mb-2">
                                        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"/></svg>
                                    </div>
                                    <p class="text-sm font-semibold text-gray-700">No stock-in records found</p>
                                    <p class="text-xs text-gray-400">Delivered items will show up here after being recorded.</p>
                                </div>
                            </td>
                        </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>

            @if($transactions instanceof \Illuminate\Pagination\LengthAwarePaginator && $transactions->hasPages())
            <div class="px-6 py-4 border-t border-gray-100 bg-gray-50/50 print:hidden">
                {{ $transactions->links() }}
            </div>
            @endif
        </div>
    </div>
</div>
@endsection
