@extends('layouts.app')
@section('title', 'Waste & Spoilage')
@section('header', 'Waste & Spoilage')
@section('subheader', 'Record damaged goods, expired ingredients, preparation spills, and loss adjustments')

@section('header-actions')
    <div class="flex items-center gap-2">
    @if(auth()->user()->canExportOrPrint())
        <a href="{{ request()->fullUrlWithQuery(['export' => 'excel']) }}" class="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-bold text-emerald-800 bg-emerald-50 border border-emerald-200 hover:bg-emerald-100 shadow-xs transition-all print:hidden">
            <svg class="w-4 h-4 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
            Export Excel
        </a>
        <a href="{{ request()->fullUrlWithQuery(['print' => 'all']) }}" target="_blank" class="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-bold text-gray-700 bg-white border border-gray-200 hover:bg-gray-50 shadow-xs transition-all print:hidden">
            <svg class="w-4 h-4 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"/></svg>
            Print Report
        </a>
    @endif
        <a href="{{ route('inventory.index') }}" class="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-semibold text-gray-700 bg-white border border-gray-200 hover:bg-gray-50 shadow-sm transition-all print:hidden">
            <svg class="w-4 h-4 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"/></svg>
            Back to Stock Overview
        </a>
    </div>
@endsection

@section('content')
{{-- Print-only header --}}
<div class="hidden print:block mb-6 pb-4 border-b border-gray-300">
    <div class="flex items-center justify-between">
        <div>
            <h1 class="text-xl font-black text-gray-900 tracking-tight">HEIM COFFEE SHOP</h1>
            <p class="text-sm font-bold text-gray-700 mt-0.5">Waste & Spoilage Incident Report</p>
        </div>
        <div class="text-right text-xs text-gray-500">
            <p>Printed: <span class="font-semibold text-gray-800">{{ now(config('app.business_timezone', 'Asia/Manila'))->format('M d, Y h:i A') }}</span></p>
            <p>Generated by: <span class="font-semibold text-gray-800">{{ auth()->user()->name }} ({{ ucfirst(auth()->user()->role) }})</span></p>
            @if(request('from') || request('to'))
                <p>Period: <span class="font-semibold text-gray-800">{{ request('from', 'Start') }} to {{ request('to', 'Present') }}</span></p>
            @endif
        </div>
    </div>
</div>

<div class="grid grid-cols-1 lg:grid-cols-12 gap-6">
    {{-- Form column --}}
    <div class="lg:col-span-4 print:hidden">
        <div class="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 sticky top-24">
            <div class="flex items-center gap-3 pb-4 mb-5 border-b border-gray-100">
                <div class="w-10 h-10 rounded-xl bg-red-50 border border-red-100 flex items-center justify-center text-red-600">
                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/></svg>
                </div>
                <div>
                    <h2 class="font-bold text-gray-900 text-base">Record Waste / Loss</h2>
                    <p class="text-xs text-gray-400">Deduct damaged or discarded stock</p>
                </div>
            </div>

            <form method="POST" action="{{ route('waste.store') }}" class="space-y-4">
                @csrf
                <div>
                    <label class="block text-xs font-bold text-gray-700 uppercase tracking-wider mb-1.5">
                        Ingredient <span class="text-red-500">*</span>
                    </label>
                    <select name="ingredient_id" required class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3.5 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-red-500 focus:bg-white transition-all">
                        <option value="">Select ingredient...</option>
                        @foreach($ingredients as $ing)
                        <option value="{{ $ing->id }}" {{ old('ingredient_id') == $ing->id ? 'selected' : '' }}>
                            {{ $ing->name }} — {{ number_format($ing->getCurrentStock(), 3) }} {{ $ing->unit }} available
                        </option>
                        @endforeach
                    </select>
                </div>

                <div>
                    <label class="block text-xs font-bold text-gray-700 uppercase tracking-wider mb-1.5">
                        Quantity Wasted <span class="text-red-500">*</span>
                    </label>
                    <input type="number" name="quantity" value="{{ old('quantity') }}" min="0.001" step="0.001" placeholder="0.00"
                        class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3.5 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-red-500 focus:bg-white font-semibold transition-all" required>
                </div>

                <div>
                    <label class="block text-xs font-bold text-gray-700 uppercase tracking-wider mb-1.5">
                        Primary Reason <span class="text-red-500">*</span>
                    </label>
                    <select name="reason" required class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3.5 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-red-500 focus:bg-white transition-all">
                        <option value="">Select reason...</option>
                        @foreach($wasteReasons as $r)
                        <option value="{{ $r }}" {{ old('reason') === $r ? 'selected' : '' }}>{{ $r }}</option>
                        @endforeach
                    </select>
                </div>

                <div>
                    <label class="block text-xs font-bold text-gray-700 uppercase tracking-wider mb-1.5">
                        Additional Notes / Incident Detail
                    </label>
                    <textarea name="notes" rows="2" placeholder="e.g. dropped milk pitcher during rush, sour batch, etc."
                        class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3.5 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-red-500 focus:bg-white transition-all">{{ old('notes') }}</textarea>
                </div>

                <div class="pt-2">
                    <button type="submit" class="inline-flex items-center justify-center w-full gap-2 rounded-xl bg-rose-600 px-4 py-2.5 text-sm font-bold text-white shadow-sm transition hover:bg-rose-700 focus:outline-none focus:ring-2 focus:ring-rose-500 focus:ring-offset-2">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/></svg>
                        Post Waste Entry
                    </button>
                </div>
            </form>
        </div>
    </div>

    {{-- History column --}}
    <div class="lg:col-span-8 print:w-full print:col-span-12">
        {{-- Filter toolbar --}}
        <div class="bg-white rounded-2xl shadow-sm border border-gray-100 p-4 mb-5 print:hidden">
            <form method="GET" class="flex flex-col sm:flex-row sm:items-end gap-3">
                <div class="flex-1 min-w-[160px]">
                    <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Filter Ingredient</label>
                    <select name="ingredient_id" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all">
                        <option value="">All Ingredients</option>
                        @foreach($ingredients as $ing)
                        <option value="{{ $ing->id }}" {{ request('ingredient_id') == $ing->id ? 'selected' : '' }}>{{ $ing->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div>
                    <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">From Date</label>
                    <input type="date" name="from" value="{{ request('from') }}" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all">
                </div>
                <div>
                    <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">To Date</label>
                    <input type="date" name="to" value="{{ request('to') }}" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all">
                </div>
                <div class="flex items-center gap-2">
                    <button type="submit" class="brand-btn-filter">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 4a1 1 0 011-1h16a1 1 0 011 1v2.586a1 1 0 01-.293.707l-6.414 6.414a1 1 0 00-.293.707V17l-4 4v-6.586a1 1 0 00-.293-.707L3.293 7.293A1 1 0 013 6.586V4z"/></svg>
                        Filter
                    </button>
                    @if(request('ingredient_id') || request('from') || request('to'))
                    <a href="{{ route('waste.index') }}" class="border border-gray-200 text-gray-600 hover:bg-gray-50 px-3.5 py-2 rounded-xl text-sm font-medium transition-colors">
                        Clear
                    </a>
                    @endif
                </div>
            </form>
        </div>

        {{-- Table --}}
        <div class="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
            <div class="px-6 py-4 border-b border-gray-100 flex items-center justify-between">
                <div>
                    <h2 class="font-bold text-gray-900 text-base">Waste Log</h2>
                    <p class="text-xs text-gray-400">Inventory reductions attributed to spoilage</p>
                </div>
                <span class="text-xs font-semibold px-2.5 py-1 rounded-full bg-red-50 text-red-700">
                    {{ $transactions instanceof \Illuminate\Pagination\LengthAwarePaginator ? $transactions->total() : $transactions->count() }} records
                </span>
            </div>

            <div class="overflow-x-auto">
                <table class="w-full text-sm">
                    <thead class="bg-gray-50/75 border-b border-gray-100 text-xs font-bold text-gray-500 uppercase tracking-wider">
                        <tr>
                            <th class="px-5 py-3.5 text-left">Ingredient</th>
                            <th class="px-5 py-3.5 text-right">Deducted</th>
                            <th class="px-5 py-3.5 text-right">Remaining Stock</th>
                            <th class="px-5 py-3.5 text-left">Reason / Notes</th>
                            <th class="px-5 py-3.5 text-left">Recorded By</th>
                            <th class="px-5 py-3.5 text-right">Date & Time</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-gray-50">
                        @forelse($transactions as $tx)
                        <tr class="hover:bg-red-50/20 transition-colors">
                            <td class="px-5 py-4 font-bold text-gray-900">{{ $tx->ingredient?->name }}</td>
                            <td class="px-5 py-4 text-right">
                                <span class="inline-flex items-center gap-0.5 font-extrabold text-sm text-red-600 bg-red-50 px-2 py-0.5 rounded-lg">
                                    -{{ number_format($tx->quantity, 3) }} {{ $tx->ingredient?->unit }}
                                </span>
                            </td>
                            <td class="px-5 py-4 text-right font-medium text-gray-600">
                                {{ number_format($tx->new_stock, 3) }} <span class="text-xs text-gray-400">{{ $tx->ingredient?->unit }}</span>
                            </td>
                            <td class="px-5 py-4">
                                <span class="inline-block px-2 py-0.5 rounded-md text-xs font-semibold bg-gray-100 text-gray-700 mb-0.5">
                                    {{ $tx->reason }}
                                </span>
                            </td>
                            <td class="px-5 py-4 text-xs font-medium text-gray-700">
                                {{ $tx->performed_by }}
                                <div class="text-[10px] text-gray-400 capitalize">{{ $tx->performed_role }}</div>
                            </td>
                            <td class="px-5 py-4 text-right text-xs text-gray-500">
                                <div class="font-medium text-gray-700">{{ $tx->created_at->copy()->timezone(config('app.business_timezone', 'Asia/Manila'))->format('M d, Y') }}</div>
                                <div class="text-[11px] text-gray-400">{{ $tx->created_at->copy()->timezone(config('app.business_timezone', 'Asia/Manila'))->format('h:i A') }}</div>
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td colspan="6" class="px-5 py-12 text-center">
                                <div class="flex flex-col items-center justify-center">
                                    <div class="w-12 h-12 rounded-2xl bg-gray-50 flex items-center justify-center text-gray-300 mb-2">
                                        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/></svg>
                                    </div>
                                    <p class="text-sm font-semibold text-gray-700">No waste records found</p>
                                    <p class="text-xs text-gray-400">Recorded ingredient spoilage will show up here.</p>
                                </div>
                            </td>
                        </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>

            @if($transactions instanceof \Illuminate\Pagination\LengthAwarePaginator && $transactions->hasPages())
            <div class="px-6 py-4 border-t border-gray-100 bg-gray-50/50 print:hidden">
                {{ $transactions->links() }}
            </div>
            @endif
        </div>
    </div>
</div>
@endsection
