@extends('layouts.app')
@section('title', 'Grab Orders Report')
@section('header', 'Grab Orders & Analytics')
@section('subheader', 'Track GrabFood delivery orders, rider codes, customer comments, and Grab pricing metrics')

@section('header-actions')
    <div class="flex items-center gap-2">
    @if(auth()->user()->canExportOrPrint())
        <a href="{{ request()->fullUrlWithQuery(['export' => 'excel']) }}" class="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-bold text-emerald-800 bg-emerald-50 border border-emerald-200 hover:bg-emerald-100 shadow-xs transition-all print:hidden">
            <svg class="w-4 h-4 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
            Export Excel
        </a>
        <button onclick="window.print()" class="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-bold text-gray-700 bg-white border border-gray-200 hover:bg-gray-50 shadow-sm transition-all print:hidden">
            <svg class="w-4 h-4 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"/></svg>
            Print Report
        </button>
    @endif
    </div>
@endsection

@section('content')
{{-- Print-only header --}}
<div class="hidden print:block mb-6 pb-4 border-b border-gray-300">
    <div class="flex items-center justify-between">
        <div>
            <h1 class="text-xl font-black text-gray-900 tracking-tight">HEIM COFFEE SHOP</h1>
            <p class="text-sm font-bold text-gray-700 mt-0.5">GrabFood Delivery Orders Report</p>
        </div>
        <div class="text-right text-xs text-gray-500">
            <p>Printed: <span class="font-semibold text-gray-800">{{ now()->format('M d, Y h:i A') }}</span></p>
            <p>Generated by: <span class="font-semibold text-gray-800">{{ auth()->user()->name }} ({{ ucfirst(auth()->user()->role) }})</span></p>
        </div>
    </div>
</div>

{{-- Metric Cards --}}
<div class="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6">
    <div class="bg-white rounded-2xl p-5 border border-emerald-100 shadow-sm relative overflow-hidden group hover:shadow-md transition-all">
        <div class="flex items-center justify-between">
            <div>
                <p class="text-xs font-bold text-emerald-700 uppercase tracking-wider mb-1">Total Grab Sales</p>
                <div class="flex items-baseline gap-2">
                    <span class="text-2xl sm:text-3xl font-black text-emerald-900">₱{{ number_format($totalGrabSales, 2) }}</span>
                </div>
            </div>
            <div class="w-12 h-12 rounded-2xl bg-emerald-50 border border-emerald-200 flex items-center justify-center text-emerald-600 group-hover:scale-110 transition-transform">
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
            </div>
        </div>
    </div>

    <div class="bg-white rounded-2xl p-5 border border-gray-100 shadow-sm relative overflow-hidden group hover:shadow-md transition-all">
        <div class="flex items-center justify-between">
            <div>
                <p class="text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Total Grab Orders</p>
                <div class="flex items-baseline gap-2">
                    <span class="text-2xl sm:text-3xl font-black text-gray-900">{{ $totalGrabOrders }}</span>
                    <span class="text-xs font-semibold text-emerald-700">({{ $completedCount }} completed)</span>
                </div>
            </div>
            <div class="w-12 h-12 rounded-2xl bg-gray-50 border border-gray-100 flex items-center justify-center text-gray-600 group-hover:scale-110 transition-transform">
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 11V7a4 4 0 00-8 0v4M5 11h14l1 12H4L5 11z"/></svg>
            </div>
        </div>
    </div>

    <div class="bg-white rounded-2xl p-5 border border-gray-100 shadow-sm relative overflow-hidden group hover:shadow-md transition-all">
        <div class="flex items-center justify-between">
            <div>
                <p class="text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Avg Grab Order Value</p>
                <div class="flex items-baseline gap-2">
                    <span class="text-2xl sm:text-3xl font-black text-gray-900">₱{{ number_format($completedCount > 0 ? $totalGrabSales / $completedCount : 0, 2) }}</span>
                </div>
            </div>
            <div class="w-12 h-12 rounded-2xl bg-gray-50 border border-gray-100 flex items-center justify-center text-gray-600 group-hover:scale-110 transition-transform">
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"/></svg>
            </div>
        </div>
    </div>
</div>

{{-- Filter Toolbar --}}
<div class="bg-white rounded-2xl shadow-sm border border-gray-100 p-4 mb-6 print:hidden">
    <form method="GET" class="flex flex-wrap items-end gap-3">
        <div class="w-full sm:w-auto flex-1 min-w-[130px]">
            <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">From Date</label>
            <input type="date" name="from" value="{{ request('from') }}" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:bg-white transition-all">
        </div>
        <div class="w-full sm:w-auto flex-1 min-w-[130px]">
            <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">To Date</label>
            <input type="date" name="to" value="{{ request('to') }}" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:bg-white transition-all">
        </div>
        <div class="w-full sm:w-auto flex-1 min-w-[140px]">
            <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Grab Order Code</label>
            <input type="text" name="grab_order_code" value="{{ request('grab_order_code') }}" placeholder="e.g. GF-2026..." class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:bg-white transition-all">
        </div>
        <div class="w-full sm:w-auto flex-1 min-w-[120px]">
            <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Rider Code</label>
            <input type="text" name="rider_code" value="{{ request('rider_code') }}" placeholder="e.g. RDR-025..." class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:bg-white transition-all">
        </div>
        <div class="w-full sm:w-auto min-w-[140px]">
            <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Product</label>
            <select name="product_id" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:bg-white transition-all">
                <option value="">All Products</option>
                @foreach($products as $prod)
                <option value="{{ $prod->id }}" {{ request('product_id') == $prod->id ? 'selected' : '' }}>{{ $prod->name }}</option>
                @endforeach
            </select>
        </div>
        <div class="w-full sm:w-auto min-w-[130px]">
            <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Cashier</label>
            <select name="cashier_name" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:bg-white transition-all">
                <option value="">All Cashiers</option>
                @foreach($cashiers as $cName)
                <option value="{{ $cName }}" {{ request('cashier_name') === $cName ? 'selected' : '' }}>{{ $cName }}</option>
                @endforeach
            </select>
        </div>
        <div class="w-full sm:w-auto min-w-[120px]">
            <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Status</label>
            <select name="status" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:bg-white transition-all">
                <option value="">All Statuses</option>
                <option value="completed" {{ request('status') === 'completed' ? 'selected' : '' }}>Completed</option>
                <option value="refunded" {{ request('status') === 'refunded' ? 'selected' : '' }}>Refunded</option>
                <option value="voided" {{ request('status') === 'voided' ? 'selected' : '' }}>Voided</option>
                <option value="held" {{ request('status') === 'held' ? 'selected' : '' }}>Held</option>
            </select>
        </div>
        <div class="flex items-center gap-2 pt-1 sm:pt-0">
            <button type="submit" class="brand-btn-filter">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 4a1 1 0 011-1h16a1 1 0 011 1v2.586a1 1 0 01-.293.707l-6.414 6.414a1 1 0 00-.293.707V17l-4 4v-6.586a1 1 0 00-.293-.707L3.293 7.293A1 1 0 013 6.586V4z"/></svg>
                Filter
            </button>
            @if(request('from') || request('to') || request('grab_order_code') || request('rider_code') || request('product_id') || request('cashier_name') || request('status'))
            <a href="{{ route('reports.grab') }}" class="border border-gray-200 text-gray-600 hover:bg-gray-50 px-3.5 py-2 rounded-xl text-sm font-medium transition-colors">
                Clear
            </a>
            @endif
        </div>
    </form>
</div>

{{-- Grab Orders Table --}}
<div class="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
    <div class="px-6 py-4 border-b border-gray-100 flex items-center justify-between">
        <div>
            <h2 class="font-bold text-gray-900 text-base">Grab Orders History</h2>
            <p class="text-xs text-gray-400">Detailed record of GrabFood orders, riders, and item comments</p>
        </div>
        <span class="text-xs font-semibold px-2.5 py-1 rounded-full bg-emerald-50 text-emerald-700 border border-emerald-100">
            {{ $orders instanceof \Illuminate\Pagination\LengthAwarePaginator ? $orders->total() : $orders->count() }} Grab orders
        </span>
    </div>

    <div class="overflow-x-auto">
        <table class="w-full text-sm">
            <thead class="bg-gray-50/75 border-b border-gray-100 text-xs font-bold text-gray-500 uppercase tracking-wider">
                <tr>
                    <th class="px-5 py-3.5 text-left">Grab Order Code</th>
                    <th class="px-5 py-3.5 text-left">Rider Code</th>
                    <th class="px-5 py-3.5 text-left">Customer / Cashier</th>
                    <th class="px-5 py-3.5 text-left">Payment Method</th>
                    <th class="px-5 py-3.5 text-left">Products & Custom Notes</th>
                    <th class="px-5 py-3.5 text-right">Total</th>
                    <th class="px-5 py-3.5 text-center">Status</th>
                    <th class="px-5 py-3.5 text-right">Date & Time</th>
                </tr>
            </thead>
            <tbody class="divide-y divide-gray-100">
                @forelse($orders as $ord)
                <tr class="hover:bg-gray-50/60 transition-colors">
                    <td class="px-5 py-3.5">
                        <span class="font-bold text-emerald-800 font-mono">{{ $ord->grab_order_code ?? '—' }}</span>
                        <div class="text-[11px] text-gray-400">{{ $ord->order_number }}</div>
                    </td>
                    <td class="px-5 py-3.5">
                        <span class="font-bold text-gray-800 font-mono">{{ $ord->rider_code ?? '—' }}</span>
                    </td>
                    <td class="px-5 py-3.5">
                        <div class="font-bold text-gray-900">{{ $ord->customer_name ?: 'Walk-in Grab' }}</div>
                        <div class="text-[11px] text-gray-400">Cashier: {{ $ord->cashier_name }}</div>
                    </td>
                    <td class="px-5 py-3.5 text-xs">
                        @forelse($ord->payments->pluck('method')->unique() as $method)
                            <span class="inline-flex items-center rounded-full px-2 py-1 font-semibold {{ strtolower($method) === 'cash' ? 'bg-emerald-50 text-emerald-700' : 'bg-blue-50 text-blue-700' }}">
                                {{ match (strtolower($method)) {
                                    'cash' => 'Cash',
                                    'grabfood', 'grab' => 'GrabFood',
                                    'online' => 'Online Payment',
                                    'pay_later' => 'Pay Later',
                                    default => ucfirst($method),
                                } }}
                            </span>
                        @empty
                            <span class="text-gray-400">—</span>
                        @endforelse
                    </td>
                    <td class="px-5 py-3.5 text-xs">
                        <ul class="space-y-1">
                            @foreach($ord->orderItems as $it)
                            <li>
                                <span class="font-bold text-gray-800">{{ $it->product?->name }}</span>
                                <span class="text-gray-500">({{ $it->productSize?->size_name }}) × {{ $it->quantity }}</span>
                                <span class="font-semibold text-gray-700">₱{{ number_format($it->subtotal, 2) }}</span>
                                @if($it->comment)
                                    <div class="text-[11px] text-amber-700 font-medium italic pl-2 border-l-2 border-amber-300">Comment: {{ $it->comment }}</div>
                                @endif
                            </li>
                            @endforeach
                        </ul>
                    </td>
                    <td class="px-5 py-3.5 text-right font-black text-gray-900 text-base">
                        ₱{{ number_format($ord->total, 2) }}
                    </td>
                    <td class="px-5 py-3.5 text-center">
                        @include('components.status-badge', ['status' => $ord->status])
                    </td>
                    <td class="px-5 py-3.5 text-right text-xs text-gray-500 whitespace-nowrap">
                        <div>{{ $ord->created_at->format('M d, Y') }}</div>
                        <div class="text-[10px] text-gray-400">{{ $ord->created_at->format('h:i A') }}</div>
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="8" class="px-5 py-12 text-center">
                        <div class="flex flex-col items-center justify-center">
                            <div class="w-12 h-12 rounded-2xl bg-gray-50 flex items-center justify-center text-gray-300 mb-2">
                                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M16 11V7a4 4 0 00-8 0v4M5 11h14l1 12H4L5 11z"/></svg>
                            </div>
                            <p class="text-sm font-semibold text-gray-700">No GrabFood orders found</p>
                            <p class="text-xs text-gray-400">Grab orders processed from the POS will appear here.</p>
                        </div>
                    </td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    @if($orders instanceof \Illuminate\Pagination\LengthAwarePaginator && $orders->hasPages())
    <div class="px-6 py-4 border-t border-gray-100 bg-gray-50/50 print:hidden">
        {{ $orders->links() }}
    </div>
    @endif
</div>
@endsection
