@extends('layouts.app')
@section('title', 'Inventory Report')
@section('header', 'Inventory Report & Audit')
@section('subheader', 'Stock health valuation, replenishment logs, and period consumption dynamics')

@section('header-actions')
    <div class="flex items-center gap-2">
        <a href="{{ request()->fullUrlWithQuery(['export' => 'excel']) }}" class="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-bold text-emerald-800 bg-emerald-50 border border-emerald-200 hover:bg-emerald-100 shadow-xs transition-all print:hidden">
            <svg class="w-4 h-4 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
            Export Excel
        </a>
        <button onclick="window.print()" class="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-bold text-gray-700 bg-white border border-gray-200 hover:bg-gray-50 shadow-sm transition-all print:hidden">
            <svg class="w-4 h-4 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"/></svg>
            Print Report
        </button>
    </div>
@endsection

@section('content')
{{-- Print-only header --}}
<div class="hidden print:block mb-6 pb-4 border-b border-gray-300">
    <div class="flex items-center justify-between">
        <div>
            <h1 class="text-xl font-black text-gray-900 tracking-tight">HEIM COFFEE SHOP</h1>
            <p class="text-sm font-bold text-gray-700 mt-0.5">Inventory Report & Audit</p>
        </div>
        <div class="text-right text-xs text-gray-500">
            <p>Period: <span class="font-semibold text-gray-800">{{ \Carbon\Carbon::parse($from)->format('M d, Y') }} — {{ \Carbon\Carbon::parse($to)->format('M d, Y') }}</span></p>
            <p>Printed: <span class="font-semibold text-gray-800">{{ now()->format('M d, Y h:i A') }}</span></p>
            <p>Generated by: <span class="font-semibold text-gray-800">{{ auth()->user()->name }} ({{ ucfirst(auth()->user()->role) }})</span></p>
        </div>
    </div>
</div>

{{-- Filter toolbar --}}
<div class="bg-white rounded-2xl shadow-sm border border-gray-100 p-4 mb-6 print:hidden">
    <form method="GET" class="flex flex-wrap items-end gap-3">
        <div>
            <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">From Date</label>
            <input type="date" name="from" value="{{ $from }}"
                class="bg-gray-50 border border-gray-200 rounded-xl px-3.5 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all">
        </div>
        <div>
            <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">To Date</label>
            <input type="date" name="to" value="{{ $to }}"
                class="bg-gray-50 border border-gray-200 rounded-xl px-3.5 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all">
        </div>
        <button type="submit" class="brand-btn-filter">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"/></svg>
            Generate
        </button>
        <div class="ml-auto text-xs text-gray-500 font-medium self-center">
            Active Period: <span class="font-bold text-gray-800">{{ \Carbon\Carbon::parse($from)->format('M d, Y') }} — {{ \Carbon\Carbon::parse($to)->format('M d, Y') }}</span>
        </div>
    </form>
</div>

{{-- Stock status summary --}}
@php
    $goodCount = $allIngredients->filter(fn($i) => $i->getStockStatus() === 'good')->count();
    $lowCount = $lowStock->count();
    $outCount = $outOfStock->count();
    $totalIngs = max(1, $goodCount + $lowCount + $outCount);
@endphp
<div class="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6">
    <div class="bg-white rounded-2xl p-5 border border-heim-100 shadow-sm relative overflow-hidden group hover:shadow-md transition-all">
        <div class="flex items-center justify-between">
            <div>
                <p class="text-xs font-bold text-heim-600 uppercase tracking-wider mb-1">Good Standing</p>
                <p class="text-3xl font-black text-heim-800">{{ $goodCount }}</p>
                <p class="text-xs text-gray-400 mt-0.5">{{ round(($goodCount / $totalIngs) * 100) }}% of catalog healthy</p>
            </div>
            <div class="w-12 h-12 rounded-2xl bg-heim-50 border border-heim-100 flex items-center justify-center text-heim-600 group-hover:scale-110 transition-transform">
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
            </div>
        </div>
        <div class="mt-3 w-full bg-heim-50 rounded-full h-1.5 overflow-hidden">
            <div class="bg-heim-500 h-1.5 rounded-full" style="width: {{ round(($goodCount / $totalIngs) * 100) }}%"></div>
        </div>
    </div>

    <div class="bg-white rounded-2xl p-5 border {{ $lowCount > 0 ? 'border-amber-200 bg-amber-50/20' : 'border-gray-100' }} shadow-sm relative overflow-hidden group hover:shadow-md transition-all">
        <div class="flex items-center justify-between">
            <div>
                <p class="text-xs font-bold {{ $lowCount > 0 ? 'text-amber-600' : 'text-gray-500' }} uppercase tracking-wider mb-1">Low Stock Warning</p>
                <p class="text-3xl font-black {{ $lowCount > 0 ? 'text-amber-700' : 'text-gray-800' }}">{{ $lowCount }}</p>
                <p class="text-xs text-gray-400 mt-0.5">Ingredients below threshold</p>
            </div>
            <div class="w-12 h-12 rounded-2xl {{ $lowCount > 0 ? 'bg-amber-100/70 text-amber-700 border border-amber-200' : 'bg-gray-50 text-gray-400 border border-gray-100' }} flex items-center justify-center group-hover:scale-110 transition-transform">
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"/></svg>
            </div>
        </div>
        <div class="mt-3 w-full bg-gray-100 rounded-full h-1.5 overflow-hidden">
            <div class="bg-amber-500 h-1.5 rounded-full" style="width: {{ round(($lowCount / $totalIngs) * 100) }}%"></div>
        </div>
    </div>

    <div class="bg-white rounded-2xl p-5 border {{ $outCount > 0 ? 'border-red-200 bg-red-50/20' : 'border-gray-100' }} shadow-sm relative overflow-hidden group hover:shadow-md transition-all">
        <div class="flex items-center justify-between">
            <div>
                <p class="text-xs font-bold {{ $outCount > 0 ? 'text-red-600' : 'text-gray-500' }} uppercase tracking-wider mb-1">Out of Stock</p>
                <p class="text-3xl font-black {{ $outCount > 0 ? 'text-red-700' : 'text-gray-800' }}">{{ $outCount }}</p>
                <p class="text-xs text-gray-400 mt-0.5">Completely depleted items</p>
            </div>
            <div class="w-12 h-12 rounded-2xl {{ $outCount > 0 ? 'bg-red-100/80 text-red-700 border border-red-200' : 'bg-gray-50 text-gray-400 border border-gray-100' }} flex items-center justify-center group-hover:scale-110 transition-transform">
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636"/></svg>
            </div>
        </div>
        <div class="mt-3 w-full bg-gray-100 rounded-full h-1.5 overflow-hidden">
            <div class="bg-red-500 h-1.5 rounded-full" style="width: {{ round(($outCount / $totalIngs) * 100) }}%"></div>
        </div>
    </div>
</div>

{{-- Alerts --}}
@if($outOfStock->isNotEmpty() || $lowStock->isNotEmpty())
<div class="bg-white rounded-2xl shadow-sm border border-amber-200 overflow-hidden mb-6">
    <div class="px-6 py-4 border-b border-amber-200 bg-amber-50/70 flex items-center justify-between">
        <div class="flex items-center gap-2.5">
            <span class="w-8 h-8 rounded-xl bg-amber-100 text-amber-700 flex items-center justify-center font-bold">⚠️</span>
            <div>
                <h2 class="font-bold text-amber-900 text-base">Replenishment Priority Queue</h2>
                <p class="text-xs text-amber-700">Immediate purchase delivery recommended to prevent stockout</p>
            </div>
        </div>
        <a href="{{ route('stock-in.index') }}" class="text-xs font-bold text-white bg-amber-600 hover:bg-amber-700 px-3 py-1.5 rounded-xl shadow-sm transition-colors print:hidden">
            Order Stock Now
        </a>
    </div>
    <div class="overflow-x-auto">
        <table class="w-full text-sm">
            <thead class="bg-amber-50/40 text-xs font-bold text-amber-800 uppercase tracking-wider">
                <tr>
                    <th class="px-5 py-3 text-left">Ingredient</th>
                    <th class="px-5 py-3 text-right">Current Available</th>
                    <th class="px-5 py-3 text-right">Required Minimum</th>
                    <th class="px-5 py-3 text-center">Urgency</th>
                </tr>
            </thead>
            <tbody class="divide-y divide-amber-100/50">
                @foreach($outOfStock->merge($lowStock) as $ing)
                @php $stat = $ing->getStockStatus(); @endphp
                <tr class="hover:bg-amber-50/30 transition-colors">
                    <td class="px-5 py-3.5 font-bold text-gray-900">{{ $ing->name }}</td>
                    <td class="px-5 py-3.5 text-right font-extrabold {{ $stat === 'out_of_stock' ? 'text-red-600' : 'text-amber-600' }}">
                        {{ number_format($ing->getCurrentStock(), 3) }} {{ $ing->unit }}
                    </td>
                    <td class="px-5 py-3.5 text-right text-gray-500 font-medium">
                        {{ number_format($ing->minimum_stock, 2) }} {{ $ing->unit }}
                    </td>
                    <td class="px-5 py-3.5 text-center">
                        @include('components.status-badge', ['status' => $stat])
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endif

{{-- Stock-in in period --}}
<div class="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden mb-6">
    <div class="px-6 py-4 border-b border-gray-100 flex items-center justify-between">
        <div>
            <h2 class="font-bold text-gray-900 text-base">Replenishments & Deliveries</h2>
            <p class="text-xs text-gray-400">Total inward transactions recorded during this selected date window</p>
        </div>
        <span class="text-xs font-semibold px-2.5 py-1 rounded-full bg-heim-50 text-heim-700">
            {{ $stockIns->count() }} shipments
        </span>
    </div>
    <div class="overflow-x-auto">
        <table class="w-full text-sm">
            <thead class="bg-gray-50/75 border-b border-gray-100 text-xs font-bold text-gray-500 uppercase tracking-wider">
                <tr>
                    <th class="px-5 py-3.5 text-left">Ingredient</th>
                    <th class="px-5 py-3.5 text-right">Quantity Received</th>
                    <th class="px-5 py-3.5 text-left">Supplier / Vendor</th>
                    <th class="px-5 py-3.5 text-left">Recorded By</th>
                    <th class="px-5 py-3.5 text-right">Delivery Date</th>
                </tr>
            </thead>
            <tbody class="divide-y divide-gray-50">
                @forelse($stockIns as $tx)
                <tr class="hover:bg-gray-50/70 transition-colors">
                    <td class="px-5 py-3.5 font-bold text-gray-900">{{ $tx->ingredient?->name ?? '—' }}</td>
                    <td class="px-5 py-3.5 text-right font-extrabold text-heim-700">
                        +{{ number_format($tx->quantity, 3) }} <span class="text-xs font-normal text-gray-400">{{ $tx->ingredient?->unit }}</span>
                    </td>
                    <td class="px-5 py-3.5 text-gray-600 text-xs font-medium">{{ $tx->supplier?->name ?? 'Direct Purchase' }}</td>
                    <td class="px-5 py-3.5 text-xs text-gray-500">{{ $tx->performed_by }}</td>
                    <td class="px-5 py-3.5 text-right text-xs text-gray-400 font-medium">
                        <div>{{ ($tx->transaction_date ?? $tx->created_at)->format('M d, Y') }}</div>
                        <div class="text-[11px]">Recorded {{ $tx->created_at->format('h:i A') }}</div>
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="5" class="px-5 py-10 text-center text-gray-400 text-sm">
                        No inward stock deliveries recorded in this period.
                    </td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>
</div>

{{-- Consumption summary --}}
<div class="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
    <div class="px-6 py-4 border-b border-gray-100 flex items-center justify-between">
        <div>
            <h2 class="font-bold text-gray-900 text-base">Net Ingredient Consumption via POS Sales</h2>
            <p class="text-xs text-gray-400 mt-0.5">
                Recipe and add-on use, less ingredients restored from voided or refunded items; older or unlinked movements are unattributed
            </p>
        </div>
        <span class="text-xs font-semibold px-2.5 py-1 rounded-full bg-gray-100 text-gray-600">
            {{ $salesConsumption->count() }} ingredients consumed
        </span>
    </div>
    <div class="overflow-x-auto">
        <table class="w-full text-sm">
            <thead class="bg-gray-50/80 border-b border-gray-100 text-xs font-bold text-gray-500 uppercase tracking-wider">
                <tr>
                    <th class="px-5 py-3.5 text-left">Ingredient</th>
                    <th class="px-5 py-3.5 text-right text-orange-600">Recipe Usage</th>
                    <th class="px-5 py-3.5 text-right text-purple-600">Add-on Usage</th>
                    <th class="px-5 py-3.5 text-right text-gray-500">Unattributed</th>
                    <th class="px-5 py-3.5 text-right text-gray-900 border-l border-gray-100">Net Consumed</th>
                    <th class="px-5 py-3.5 text-right">Current Stock</th>
                </tr>
            </thead>
            <tbody class="divide-y divide-gray-50">
                @forelse($salesConsumption as $row)
                @php $stockStatus = $row->ingredient?->getStockStatus(); @endphp
                <tr class="hover:bg-gray-50/60 transition-colors {{ $stockStatus === 'out_of_stock' ? 'bg-red-50/20' : ($stockStatus === 'low_stock' ? 'bg-amber-50/20' : '') }}">
                    <td class="px-5 py-3.5">
                        <div class="font-bold text-gray-900">{{ $row->ingredient?->name }}</div>
                        <span class="text-[10px] font-bold px-1.5 py-0.5 rounded bg-gray-100 text-gray-500 uppercase">
                            {{ $row->ingredient?->unit }}
                        </span>
                    </td>
                    <td class="px-5 py-3.5 text-right">
                        @if((float)$row->recipe_consumed > 0)
                            <span class="inline-block px-2 py-0.5 rounded-lg text-xs font-bold bg-orange-50 text-orange-700 border border-orange-100">
                                {{ number_format($row->recipe_consumed, 3) }}
                            </span>
                        @else
                            <span class="text-gray-300 text-xs">—</span>
                        @endif
                    </td>
                    <td class="px-5 py-3.5 text-right">
                        @if((float)$row->addon_consumed > 0)
                            <span class="inline-block px-2 py-0.5 rounded-lg text-xs font-bold bg-purple-50 text-purple-700 border border-purple-100">
                                {{ number_format($row->addon_consumed, 3) }}
                            </span>
                        @else
                            <span class="text-gray-300 text-xs">—</span>
                        @endif
                    </td>
                    <td class="px-5 py-3.5 text-right">
                        @if((float)$row->unattributed_consumed > 0)
                            <span class="inline-block px-2 py-0.5 rounded-lg text-xs font-bold bg-gray-100 text-gray-600 border border-gray-200">
                                {{ number_format($row->unattributed_consumed, 3) }}
                            </span>
                        @else
                            <span class="text-gray-300 text-xs">—</span>
                        @endif
                    </td>
                    <td class="px-5 py-3.5 text-right border-l border-gray-100">
                        <span class="font-extrabold text-gray-900">{{ number_format($row->total_consumed, 3) }}</span>
                        <span class="text-xs text-gray-400 ml-0.5">{{ $row->ingredient?->unit }}</span>
                    </td>
                    <td class="px-5 py-3.5 text-right">
                        <span class="font-bold {{ $stockStatus === 'out_of_stock' ? 'text-red-600' : ($stockStatus === 'low_stock' ? 'text-amber-600' : 'text-gray-700') }}">
                            {{ number_format($row->ingredient?->getCurrentStock() ?? 0, 3) }}
                        </span>
                        <span class="text-xs text-gray-400 ml-0.5">{{ $row->ingredient?->unit }}</span>
                        @if($stockStatus !== 'good')
                            <span class="ml-1 text-[10px] font-bold px-1 py-0.5 rounded {{ $stockStatus === 'out_of_stock' ? 'bg-red-100 text-red-700' : 'bg-amber-100 text-amber-700' }}">
                                {{ $stockStatus === 'out_of_stock' ? 'OUT' : 'LOW' }}
                            </span>
                        @endif
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="6" class="px-5 py-14 text-center text-gray-400 text-sm">
                        <svg class="w-10 h-10 mx-auto text-gray-300 mb-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/>
                        </svg>
                        No sales consumption recorded for this date window.
                    </td>
                </tr>
                @endforelse
            </tbody>
            @if($salesConsumption->isNotEmpty())
            <tfoot class="border-t-2 border-gray-200 bg-gray-50/70 text-xs font-bold text-gray-700">
                @foreach($consumptionTotals as $unit => $totals)
                    <tr>
                        <td class="px-5 py-3.5">PERIOD TOTAL ({{ $unit }})</td>
                        <td class="px-5 py-3.5 text-right text-orange-700">
                            {{ number_format($totals['recipe_consumed'], 3) }} {{ $unit }}
                        </td>
                        <td class="px-5 py-3.5 text-right text-purple-700">
                            {{ number_format($totals['addon_consumed'], 3) }} {{ $unit }}
                        </td>
                        <td class="px-5 py-3.5 text-right text-gray-600">
                            {{ number_format($totals['unattributed_consumed'], 3) }} {{ $unit }}
                        </td>
                        <td class="px-5 py-3.5 text-right text-gray-900 border-l border-gray-200">
                            {{ number_format($totals['total_consumed'], 3) }} {{ $unit }}
                        </td>
                        <td class="px-5 py-3.5"></td>
                    </tr>
                @endforeach
            </tfoot>
            @endif
        </table>
    </div>
</div>
@endsection
