@extends('layouts.app')
@section('title', 'Sales Reports')
@section('header', 'Sales Reports & Analytics')
@section('subheader', 'Financial revenue, order velocity, payment distribution, and cashier performance')

@section('header-actions')
    <div class="flex items-center gap-2">
        <a href="{{ request()->fullUrlWithQuery(['export' => 'excel']) }}" class="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-bold text-emerald-800 bg-emerald-50 border border-emerald-200 hover:bg-emerald-100 shadow-xs transition-all print:hidden">
            <svg class="w-4 h-4 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
            Export Excel
        </a>
        <button onclick="window.print()" class="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-bold text-gray-700 bg-white border border-gray-200 hover:bg-gray-50 shadow-sm transition-all print:hidden">
            <svg class="w-4 h-4 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"/></svg>
            Print Report
        </button>
    </div>
@endsection

@section('content')
{{-- Print-only header --}}
<div class="hidden print:block mb-6 pb-4 border-b border-gray-300">
    <div class="flex items-center justify-between">
        <div>
            <h1 class="text-xl font-black text-gray-900 tracking-tight">HEIM COFFEE SHOP</h1>
            <p class="text-sm font-bold text-gray-700 mt-0.5">Sales Report & Analytics</p>
        </div>
        <div class="text-right text-xs text-gray-500">
            <p>Scope: <span class="font-semibold text-gray-800">{{ \Carbon\Carbon::parse($startDate)->format('M d, Y') }} — {{ \Carbon\Carbon::parse($endDate)->format('M d, Y') }}</span></p>
            <p>Printed: <span class="font-semibold text-gray-800">{{ now(config('app.business_timezone', 'Asia/Manila'))->format('M d, Y h:i A') }}</span></p>
            <p>Generated by: <span class="font-semibold text-gray-800">{{ auth()->user()->name }} ({{ ucfirst(auth()->user()->role) }})</span></p>
        </div>
    </div>
</div>

{{-- Report controls --}}
<div class="bg-white rounded-2xl shadow-sm border border-gray-100 p-4 mb-6 print:hidden">
    <form method="GET" class="flex flex-wrap items-end gap-3">
        <div class="w-44">
            <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Report Interval</label>
            <select name="type" id="report-type" onchange="toggleDateInputs(this.value)"
                class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all font-medium">
                @foreach(['daily'=>'Daily Report','weekly'=>'Weekly Report','monthly'=>'Monthly Report','yearly'=>'Yearly Report','custom'=>'Custom Date Range','all'=>'All Time'] as $val => $label)
                <option value="{{ $val }}" {{ $type === $val ? 'selected' : '' }}>{{ $label }}</option>
                @endforeach
            </select>
        </div>

        <div id="date-input" class="{{ $type === 'custom' || $type === 'all' ? 'hidden' : '' }}">
            <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Anchor Date</label>
            <input type="date" name="date" value="{{ $date }}"
                class="bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all">
        </div>

        <div id="range-inputs" class="{{ $type === 'custom' ? '' : 'hidden' }} flex gap-2">
            <div>
                <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">From</label>
                <input type="date" name="from" value="{{ $from }}" {{ $type === 'custom' ? 'required' : '' }}
                    class="bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all">
            </div>
            <div>
                <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">To</label>
                <input type="date" name="to" value="{{ $to }}" {{ $type === 'custom' ? 'required' : '' }}
                    class="bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all">
            </div>
        </div>

        <button type="submit" class="brand-btn-filter">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"/></svg>
            Generate
        </button>

        <div class="ml-auto text-xs text-gray-500 font-medium self-center">
            Scope: <span class="font-bold text-gray-800">{{ \Carbon\Carbon::parse($startDate)->format('M d, Y') }} — {{ \Carbon\Carbon::parse($endDate)->format('M d, Y') }}</span>
        </div>
    </form>
</div>

{{-- KPIs --}}
<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
    <div class="bg-gradient-to-br from-heim-700 via-heim-800 to-heim-900 rounded-2xl p-5 text-white shadow-md shadow-heim-900/10 relative overflow-hidden group">
        <div class="flex items-center justify-between">
            <div>
                <p class="text-xs font-bold text-heim-200 uppercase tracking-wider mb-1">Total Gross Sales</p>
                <p class="text-2xl sm:text-3xl font-black">₱{{ number_format($totalSales, 2) }}</p>
            </div>
            <div class="w-12 h-12 rounded-2xl bg-white/10 flex items-center justify-center text-white backdrop-blur-sm group-hover:scale-110 transition-transform">
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
            </div>
        </div>
        <p class="text-[11px] text-heim-300 mt-3 flex items-center gap-1">
            <span>Net of voids & canceled orders</span>
        </p>
    </div>

    <div class="bg-white rounded-2xl p-5 shadow-sm border border-gray-100 relative overflow-hidden group hover:shadow-md transition-all">
        <div class="flex items-center justify-between">
            <div>
                <p class="text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Sales Orders</p>
                <p class="text-2xl sm:text-3xl font-black text-gray-900">{{ number_format($totalOrders) }}</p>
            </div>
            <div class="w-12 h-12 rounded-2xl bg-blue-50 border border-blue-100 flex items-center justify-center text-blue-600 group-hover:scale-110 transition-transform">
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z"/></svg>
            </div>
        </div>
        <p class="text-[11px] text-gray-400 mt-3">
            Avg: <span class="font-bold text-gray-700">₱{{ number_format($totalOrders > 0 ? $totalSales / $totalOrders : 0, 2) }}</span> / order
        </p>
    </div>

    <div class="bg-white rounded-2xl p-5 shadow-sm border border-gray-100 relative overflow-hidden group hover:shadow-md transition-all">
        <div class="flex items-center justify-between">
            <div>
                <p class="text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Beverages & Items</p>
                <p class="text-2xl sm:text-3xl font-black text-gray-900">{{ number_format($totalItems) }}</p>
            </div>
            <div class="w-12 h-12 rounded-2xl bg-amber-50 border border-amber-100 flex items-center justify-center text-amber-600 group-hover:scale-110 transition-transform">
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"/></svg>
            </div>
        </div>
        <p class="text-[11px] text-gray-400 mt-3">
            Total product units dispensed
        </p>
    </div>

    <div class="bg-white rounded-2xl p-5 shadow-sm border {{ $refundsCount > 0 ? 'border-red-200 bg-red-50/30' : 'border-gray-100' }} relative overflow-hidden group hover:shadow-md transition-all">
        <div class="flex items-center justify-between">
            <div>
                <p class="text-xs font-bold {{ $refundsCount > 0 ? 'text-red-600' : 'text-gray-500' }} uppercase tracking-wider mb-1">Returns / Refunds</p>
                <p class="text-2xl sm:text-3xl font-black {{ $refundsCount > 0 ? 'text-red-700' : 'text-gray-900' }}">{{ $refundsCount }}</p>
            </div>
            <div class="w-12 h-12 rounded-2xl {{ $refundsCount > 0 ? 'bg-red-100 text-red-600 border border-red-200' : 'bg-gray-50 text-gray-400 border border-gray-100' }} flex items-center justify-center group-hover:scale-110 transition-transform">
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 15v-1a4 4 0 00-4-4H4m0 0l4-4m-4 4l4 4m12 0v1a4 4 0 01-4 4H8"/></svg>
            </div>
        </div>
        <p class="text-[11px] {{ $refundsCount > 0 ? 'text-red-500 font-bold' : 'text-gray-400' }} mt-3">
            @if($refundsCount > 0)
                -₱{{ number_format($refundsAmount, 2) }} total refunded
            @else
                No refund deductions
            @endif
        </p>
    </div>
</div>

<div class="grid grid-cols-1 lg:grid-cols-12 gap-6 mb-6">
    {{-- Payment breakdown --}}
    <div class="lg:col-span-5 bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden flex flex-col">
        <div class="px-6 py-4 border-b border-gray-100 flex items-center justify-between">
            <div>
                <h2 class="font-bold text-gray-900 text-base">Payment Methods</h2>
                <p class="text-xs text-gray-400">Share of total tender volume</p>
            </div>
            <span class="text-xs font-semibold text-gray-400">Tender breakdown</span>
        </div>
        <div class="p-6 space-y-5 flex-1 flex flex-col justify-around">
            @php $pmGrandTotal = max(0.01, $paymentBreakdown->sum('total')); @endphp
            @forelse($paymentBreakdown as $pm)
            @php $pct = round(($pm->total / $pmGrandTotal) * 100); @endphp
            @php 
                $isCash = strtolower($pm->method) === 'cash'; 
                $label  = $isCash ? 'Cash' : 'Online Payment';
            @endphp
            <div>
                <div class="flex items-center justify-between mb-1.5">
                    <div class="flex items-center gap-2.5">
                        <span class="w-8 h-8 rounded-xl {{ $isCash ? 'bg-emerald-50 text-emerald-700' : 'bg-blue-50 text-blue-700' }} flex items-center justify-center font-bold text-sm">
                            {{ $isCash ? '₱' : '📱' }}
                        </span>
                        <div>
                            <span class="font-bold text-gray-800">{{ $label }}</span>
                            <span class="text-xs text-gray-400 ml-1">({{ $pm->count }} tx)</span>
                        </div>
                    </div>
                    <div class="text-right">
                        <span class="font-extrabold text-gray-900">₱{{ number_format($pm->total, 2) }}</span>
                        <span class="text-xs text-gray-400 ml-1">({{ $pct }}%)</span>
                    </div>
                </div>
                <div class="w-full bg-gray-100 rounded-full h-2 overflow-hidden">
                    <div class="h-2 rounded-full transition-all duration-500 {{ $isCash ? 'bg-emerald-500' : 'bg-blue-500' }}"
                         style="width: {{ $pct }}%"></div>
                </div>
            </div>
            @empty
            <div class="text-center py-8 text-gray-400 text-sm">No transaction records in this period.</div>
            @endforelse
        </div>
    </div>

    {{-- Best sellers --}}
    <div class="lg:col-span-7 bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
        <div class="px-6 py-4 border-b border-gray-100 flex items-center justify-between">
            <div>
                <h2 class="font-bold text-gray-900 text-base">Top Selling Products</h2>
                <p class="text-xs text-gray-400">Ranked by units sold and revenue contribution</p>
            </div>
            <span class="text-xs font-semibold px-2.5 py-1 rounded-full bg-heim-50 text-heim-700">
                Top {{ $bestSellers->count() }} items
            </span>
        </div>
        <div class="overflow-x-auto">
            <table class="w-full text-sm">
                <thead class="bg-gray-50/75 border-b border-gray-100 text-xs font-bold text-gray-500 uppercase tracking-wider">
                    <tr>
                        <th class="px-5 py-3 text-center w-12">#</th>
                        <th class="px-5 py-3 text-left">Product / Size</th>
                        <th class="px-5 py-3 text-right">Units Sold</th>
                        <th class="px-5 py-3 text-right">Revenue</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-gray-50">
                    @forelse($bestSellers as $i => $item)
                    <tr class="hover:bg-gray-50/70 transition-colors">
                        <td class="px-5 py-3.5 text-center">
                            @if($i === 0)
                                <span class="w-6 h-6 rounded-full bg-amber-100 text-amber-800 font-black text-xs inline-flex items-center justify-center">1</span>
                            @elseif($i === 1)
                                <span class="w-6 h-6 rounded-full bg-slate-200 text-slate-700 font-bold text-xs inline-flex items-center justify-center">2</span>
                            @elseif($i === 2)
                                <span class="w-6 h-6 rounded-full bg-orange-100 text-orange-800 font-bold text-xs inline-flex items-center justify-center">3</span>
                            @else
                                <span class="text-xs text-gray-400 font-semibold">{{ $i + 1 }}</span>
                            @endif
                        </td>
                        <td class="px-5 py-3.5">
                            <div class="font-bold text-gray-900">{{ $item->product }}</div>
                            <span class="text-xs text-gray-400">{{ $item->size_name ?? 'Standard' }}</span>
                        </td>
                        <td class="px-5 py-3.5 text-right font-extrabold text-heim-700">
                            {{ number_format($item->qty_sold) }}
                            <span class="text-xs text-gray-400 font-normal">cups</span>
                        </td>
                        <td class="px-5 py-3.5 text-right font-bold text-gray-900">
                            ₱{{ number_format($item->revenue, 2) }}
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="4" class="px-5 py-10 text-center text-gray-400 text-sm">
                            No product sales recorded in this period.
                        </td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
</div>

{{-- Sales by cashier --}}
<div class="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden mb-6">
    <div class="px-6 py-4 border-b border-gray-100 flex items-center justify-between">
        <div>
            <h2 class="font-bold text-gray-900 text-base">Cashier Performance</h2>
            <p class="text-xs text-gray-400">Order count, total sales volume, and ticket averages per staff member</p>
        </div>
        <span class="text-xs font-semibold px-2.5 py-1 rounded-full bg-gray-100 text-gray-600">
            {{ $byCashier->count() }} active staff
        </span>
    </div>
    <div class="overflow-x-auto">
        <table class="w-full text-sm">
            <thead class="bg-gray-50/75 border-b border-gray-100 text-xs font-bold text-gray-500 uppercase tracking-wider">
                <tr>
                    <th class="px-5 py-3.5 text-left">Cashier</th>
                    <th class="px-5 py-3.5 text-right">Orders Processed</th>
                    <th class="px-5 py-3.5 text-right">Total Sales Handled</th>
                    <th class="px-5 py-3.5 text-right">Average Ticket Size</th>
                </tr>
            </thead>
            <tbody class="divide-y divide-gray-50">
                @forelse($byCashier as $c)
                <tr class="hover:bg-gray-50/70 transition-colors">
                    <td class="px-5 py-4">
                        <div class="flex items-center gap-3">
                            <div class="w-9 h-9 rounded-xl bg-heim-100 text-heim-800 font-bold text-xs flex items-center justify-center">
                                {{ strtoupper(substr($c->cashier_name ?? 'C', 0, 2)) }}
                            </div>
                            <div>
                                <div class="font-bold text-gray-900">{{ $c->cashier_name }}</div>
                                <div class="text-[11px] text-gray-400">Staff Member</div>
                            </div>
                        </div>
                    </td>
                    <td class="px-5 py-4 text-right">
                        <span class="font-bold text-gray-800">{{ number_format($c->total_orders) }}</span>
                        <span class="text-xs text-gray-400 ml-0.5">orders</span>
                    </td>
                    <td class="px-5 py-4 text-right">
                        <span class="font-extrabold text-base text-heim-700">₱{{ number_format($c->total_sales, 2) }}</span>
                    </td>
                    <td class="px-5 py-4 text-right">
                        <span class="font-bold text-gray-700">₱{{ number_format($c->total_sales / max(1, $c->total_orders), 2) }}</span>
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="4" class="px-5 py-10 text-center text-gray-400 text-sm">No cashier data recorded.</td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>
</div>

{{-- Daily trend (for multi-day reports) --}}
@if($dailyBreakdown->count() > 1)
<div class="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
    <div class="px-6 py-4 border-b border-gray-100 flex items-center justify-between">
        <div>
            <h2 class="font-bold text-gray-900 text-base">Daily Sales Breakdown</h2>
            <p class="text-xs text-gray-400">Day-by-day trajectory across this reporting window</p>
        </div>
        <span class="text-xs font-semibold px-2.5 py-1 rounded-full bg-gray-100 text-gray-600">
            {{ $dailyBreakdown->count() }} days
        </span>
    </div>
    <div class="overflow-x-auto">
        <table class="w-full text-sm">
            <thead class="bg-gray-50/75 border-b border-gray-100 text-xs font-bold text-gray-500 uppercase tracking-wider">
                <tr>
                    <th class="px-5 py-3.5 text-left">Date</th>
                    <th class="px-5 py-3.5 text-right">Orders</th>
                    <th class="px-5 py-3.5 text-right">Gross Sales</th>
                </tr>
            </thead>
            <tbody class="divide-y divide-gray-50">
                @foreach($dailyBreakdown as $day)
                <tr class="hover:bg-gray-50/70 transition-colors">
                    <td class="px-5 py-3.5 font-medium text-gray-800">
                        {{ \Carbon\Carbon::parse($day->date)->format('D, M d, Y') }}
                    </td>
                    <td class="px-5 py-3.5 text-right text-gray-600">
                        {{ number_format($day->orders) }}
                    </td>
                    <td class="px-5 py-3.5 text-right font-bold text-heim-700">
                        ₱{{ number_format($day->total, 2) }}
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endif

@push('scripts')
<script>
function toggleDateInputs(type) {
    var dateInput = document.getElementById('date-input');
    var rangeInputs = document.getElementById('range-inputs');
    var rangeFields = rangeInputs ? rangeInputs.querySelectorAll('input[type="date"]') : [];
    if (dateInput) {
        dateInput.classList.toggle('hidden', type === 'custom' || type === 'all');
    }
    if (rangeInputs) {
        rangeInputs.classList.toggle('hidden', type !== 'custom');
    }
    rangeFields.forEach(function (field) {
        field.required = type === 'custom';
    });
}
</script>
@endpush
@endsection
