@extends('layouts.app')
@section('title', 'Cashier Shifts Report')
@section('header', 'Cashier Shifts & Cash Reconciliation')
@section('subheader', 'Audit shift-in/shift-out logs, beginning cash, cash sales, actual cash counts, and variance differences')

@section('header-actions')
    <div class="flex items-center gap-2">
    @if(auth()->user()->canExportOrPrint())
        <a href="{{ request()->fullUrlWithQuery(['export' => 'excel']) }}" class="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-bold text-emerald-800 bg-emerald-50 border border-emerald-200 hover:bg-emerald-100 shadow-xs transition-all print:hidden">
            <svg class="w-4 h-4 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
            Export Excel
        </a>
        <button onclick="window.print()" class="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-bold text-gray-700 bg-white border border-gray-200 hover:bg-gray-50 shadow-sm transition-all print:hidden">
            <svg class="w-4 h-4 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"/></svg>
            Print Report
        </button>
    @endif
    </div>
@endsection

@section('content')
{{-- Print-only header --}}
<div class="hidden print:block mb-6 pb-4 border-b border-gray-300">
    <div class="flex items-center justify-between">
        <div>
            <h1 class="text-xl font-black text-gray-900 tracking-tight">HEIM COFFEE SHOP</h1>
            <p class="text-sm font-bold text-gray-700 mt-0.5">Cashier Shift Management & Audit Report</p>
        </div>
        <div class="text-right text-xs text-gray-500">
            <p>Printed: <span class="font-semibold text-gray-800">{{ now()->timezone(config('app.business_timezone'))->format('M d, Y h:i A') }}</span></p>
            <p>Generated by: <span class="font-semibold text-gray-800">{{ auth()->user()->name }} ({{ ucfirst(auth()->user()->role) }})</span></p>
        </div>
    </div>
</div>

{{-- Metric Cards --}}
<div class="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6">
    <div class="bg-white rounded-2xl p-5 border border-heim-100 shadow-sm relative overflow-hidden group hover:shadow-md transition-all">
        <div class="flex items-center justify-between">
            <div>
                <p class="text-xs font-bold text-heim-600 uppercase tracking-wider mb-1">Total Shift Cash Sales</p>
                <div class="flex items-baseline gap-2">
                    <span class="text-2xl sm:text-3xl font-black text-heim-900">₱{{ number_format($totalCashSales, 2) }}</span>
                </div>
            </div>
            <div class="w-12 h-12 rounded-2xl bg-heim-50 border border-heim-100 flex items-center justify-center text-heim-600 group-hover:scale-110 transition-transform">
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 9V7a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2m2 4h10a2 2 0 002-2v-6a2 2 0 00-2-2H9a2 2 0 00-2 2v6a2 2 0 002 2zm7-5a2 2 0 11-4 0 2 2 0 014 0z"/></svg>
            </div>
        </div>
    </div>

    <div class="bg-white rounded-2xl p-5 border border-gray-100 shadow-sm relative overflow-hidden group hover:shadow-md transition-all">
        <div class="flex items-center justify-between">
            <div>
                <p class="text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Recorded Shifts</p>
                <div class="flex items-baseline gap-2">
                    <span class="text-2xl sm:text-3xl font-black text-gray-900">{{ $totalShifts }}</span>
                    <span class="text-xs text-gray-500 font-medium">shifts</span>
                </div>
            </div>
            <div class="w-12 h-12 rounded-2xl bg-gray-50 border border-gray-100 flex items-center justify-center text-gray-600 group-hover:scale-110 transition-transform">
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
            </div>
        </div>
    </div>

    <div class="bg-white rounded-2xl p-5 border {{ $totalVariance != 0 ? ($totalVariance < 0 ? 'border-rose-200 bg-rose-50/20' : 'border-emerald-200 bg-emerald-50/20') : 'border-gray-100' }} shadow-sm relative overflow-hidden group hover:shadow-md transition-all">
        <div class="flex items-center justify-between">
            <div>
                <p class="text-xs font-bold {{ $totalVariance < 0 ? 'text-rose-600' : ($totalVariance > 0 ? 'text-emerald-600' : 'text-gray-500') }} uppercase tracking-wider mb-1">Net Cash Variance</p>
                <div class="flex items-baseline gap-2">
                    <span class="text-2xl sm:text-3xl font-black {{ $totalVariance < 0 ? 'text-rose-700' : ($totalVariance > 0 ? 'text-emerald-700' : 'text-gray-900') }}">
                        {{ $totalVariance >= 0 ? '+' : '' }}₱{{ number_format($totalVariance, 2) }}
                    </span>
                </div>
            </div>
            <div class="w-12 h-12 rounded-2xl {{ $totalVariance < 0 ? 'bg-rose-100 text-rose-700 border border-rose-200' : 'bg-emerald-100 text-emerald-700 border border-emerald-200' }} flex items-center justify-center group-hover:scale-110 transition-transform">
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 7h6m0 10v-3m-3 3h.01M9 17h.01M9 14h.01M12 14h.01M15 11h.01M12 11h.01M9 11h.01M7 21h10a2 2 0 002-2V5a2 2 0 00-2-2H7a2 2 0 00-2 2v14a2 2 0 002 2z"/></svg>
            </div>
        </div>
    </div>
</div>

{{-- Filter Toolbar --}}
<div class="bg-white rounded-2xl shadow-sm border border-gray-100 p-4 mb-6 print:hidden">
    <form method="GET" class="flex flex-wrap items-end gap-3">
        <div class="w-full sm:w-auto flex-1 min-w-[140px]">
            <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">From Date</label>
            <input type="date" name="from" value="{{ request('from') }}" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all">
        </div>
        <div class="w-full sm:w-auto flex-1 min-w-[140px]">
            <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">To Date</label>
            <input type="date" name="to" value="{{ request('to') }}" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all">
        </div>
        <div class="w-full sm:w-auto min-w-[160px]">
            <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Cashier</label>
            <select name="cashier_name" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all">
                <option value="">All Cashiers</option>
                @foreach($cashiers as $cName)
                <option value="{{ $cName }}" {{ request('cashier_name') === $cName ? 'selected' : '' }}>{{ $cName }}</option>
                @endforeach
            </select>
        </div>
        <div class="w-full sm:w-auto min-w-[130px]">
            <label class="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Status</label>
            <select name="status" class="w-full bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-heim-500 focus:bg-white transition-all">
                <option value="">All Statuses</option>
                <option value="open" {{ request('status') === 'open' ? 'selected' : '' }}>Open</option>
                <option value="balanced" {{ request('status') === 'balanced' ? 'selected' : '' }}>Balanced</option>
                <option value="short" {{ request('status') === 'short' ? 'selected' : '' }}>Short</option>
                <option value="over" {{ request('status') === 'over' ? 'selected' : '' }}>Over</option>
                <option value="reviewed" {{ request('status') === 'reviewed' ? 'selected' : '' }}>Reviewed</option>
            </select>
        </div>
        <div class="flex items-center gap-2 pt-1 sm:pt-0">
            <button type="submit" class="brand-btn-filter">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 4a1 1 0 011-1h16a1 1 0 011 1v2.586a1 1 0 01-.293.707l-6.414 6.414a1 1 0 00-.293.707V17l-4 4v-6.586a1 1 0 00-.293-.707L3.293 7.293A1 1 0 013 6.586V4z"/></svg>
                Filter
            </button>
            @if(request('from') || request('to') || request('cashier_name') || request('status'))
            <a href="{{ route('reports.shifts') }}" class="border border-gray-200 text-gray-600 hover:bg-gray-50 px-3.5 py-2 rounded-xl text-sm font-medium transition-colors">
                Clear
            </a>
            @endif
        </div>
    </form>
</div>

{{-- Shifts Table --}}
<div class="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
    <div class="px-6 py-4 border-b border-gray-100 flex items-center justify-between">
        <div>
            <h2 class="font-bold text-gray-900 text-base">Shifts Audit Ledger</h2>
            <p class="text-xs text-gray-400">Log of shift start times, beginning cash, cash sales, expected vs actual cash counts</p>
        </div>
        <span class="text-xs font-semibold px-2.5 py-1 rounded-full bg-gray-100 text-gray-600">
            {{ $shifts instanceof \Illuminate\Pagination\LengthAwarePaginator ? $shifts->total() : $shifts->count() }} shifts
        </span>
    </div>

    <div class="overflow-x-auto">
        <table class="w-full text-sm">
            <thead class="bg-gray-50/75 border-b border-gray-100 text-xs font-bold text-gray-500 uppercase tracking-wider">
                <tr>
                    <th class="px-5 py-3.5 text-left">Cashier</th>
                    <th class="px-5 py-3.5 text-left">Shift Timing</th>
                    <th class="px-5 py-3.5 text-right">Beginning Cash</th>
                    <th class="px-5 py-3.5 text-right">Cash Sales</th>
                    <th class="px-5 py-3.5 text-right">Debt Collections (Cash)</th>
                    <th class="px-5 py-3.5 text-right">Cash Refunds</th>
                    <th class="px-5 py-3.5 text-right">Cash Voids</th>
                    <th class="px-5 py-3.5 text-right">Expected Cash</th>
                    <th class="px-5 py-3.5 text-right">Actual Cash</th>
                    <th class="px-5 py-3.5 text-right">Variance</th>
                    <th class="px-5 py-3.5 text-left">Notes / Comment</th>
                    <th class="px-5 py-3.5 text-center">Status</th>
                </tr>
            </thead>
            <tbody class="divide-y divide-gray-100">
                @forelse($shifts as $s)
                <tr class="hover:bg-gray-50/60 transition-colors">
                    <td class="px-5 py-3.5">
                        <a href="{{ route('reports.shifts.show', $s) }}" class="font-bold text-gray-900 hover:text-heim-700">{{ $s->cashier_name }}</a>
                        <div class="text-[11px] text-gray-400">Shift #{{ $s->id }}</div>
                    </td>
                    <td class="px-5 py-3.5 text-xs text-gray-600">
                        <div class="font-bold text-gray-800">{{ $s->shift_date ? $s->shift_date->format('M d, Y') : '' }}</div>
                        <div class="text-[11px] text-gray-500">
                            In: {{ $s->localStartTime()?->format('M d, h:i A') ?? '—' }}
                            @if($s->end_time)
                                | Out: {{ $s->localEndTime()->format('M d, h:i A') }}
                            @else
                                | <span class="text-emerald-600 font-bold">Active</span>
                            @endif
                        </div>
                    </td>
                    <td class="px-5 py-3.5 text-right font-semibold text-gray-700">₱{{ number_format($s->beginning_cash, 2) }}</td>
                    <td class="px-5 py-3.5 text-right font-semibold text-gray-700">₱{{ number_format($s->cash_sales, 2) }}</td>
                    <td class="px-5 py-3.5 text-right font-semibold text-gray-700">₱{{ number_format($s->debt_cash_collections, 2) }}</td>
                    <td class="px-5 py-3.5 text-right font-semibold text-rose-700">−₱{{ number_format($s->cash_refunds, 2) }}</td>
                    <td class="px-5 py-3.5 text-right font-semibold text-rose-700">−₱{{ number_format($s->cash_voids, 2) }}</td>
                    <td class="px-5 py-3.5 text-right font-bold text-gray-900">₱{{ number_format($s->expected_cash, 2) }}</td>
                    <td class="px-5 py-3.5 text-right font-bold text-gray-900">
                        {{ $s->actual_cash !== null ? '₱' . number_format($s->actual_cash, 2) : '—' }}
                    </td>
                    <td class="px-5 py-3.5 text-right font-bold">
                        @if($s->difference !== null)
                            <span class="{{ $s->difference < 0 ? 'text-rose-600' : ($s->difference > 0 ? 'text-emerald-600' : 'text-gray-600') }}">
                                {{ $s->difference >= 0 ? '+' : '' }}₱{{ number_format($s->difference, 2) }}
                            </span>
                        @else
                            <span class="text-gray-400">—</span>
                        @endif
                    </td>
                    <td class="px-5 py-3.5 text-xs text-gray-500 max-w-xs truncate" title="{{ $s->notes }}">
                        {{ $s->notes ?? '—' }}
                    </td>
                    <td class="px-5 py-3.5 text-center">
                        @if($s->isOpen())
                            <span class="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-bold bg-emerald-100 text-emerald-800">
                                Open · View
                            </span>
                        @elseif($s->status === 'reviewed')
                            <span class="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-bold bg-blue-100 text-blue-800">Reviewed</span>
                            <a href="{{ route('reports.shifts.show', $s) }}" class="ml-1 text-xs font-semibold text-heim-700 hover:underline">Summary</a>
                        @else
                            <span class="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-bold bg-gray-100 text-gray-700">
                                {{ $s->difference < 0 ? 'Short' : ($s->difference > 0 ? 'Over' : 'Balanced') }}
                            </span>
                            <a href="{{ route('reports.shifts.show', $s) }}" class="ml-1 text-xs font-semibold text-heim-700 hover:underline">Summary</a>
                        @endif
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="12" class="px-5 py-12 text-center">
                        <div class="flex flex-col items-center justify-center">
                            <div class="w-12 h-12 rounded-2xl bg-gray-50 flex items-center justify-center text-gray-300 mb-2">
                                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
                            </div>
                            <p class="text-sm font-semibold text-gray-700">No cashier shifts found</p>
                            <p class="text-xs text-gray-400">Shift In and Shift Out records will appear here.</p>
                        </div>
                    </td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    @if($shifts instanceof \Illuminate\Pagination\LengthAwarePaginator && $shifts->hasPages())
    <div class="px-6 py-4 border-t border-gray-100 bg-gray-50/50 print:hidden">
        {{ $shifts->links() }}
    </div>
    @endif
</div>

<section class="mt-6 rounded-2xl border border-gray-100 bg-white p-5 shadow-sm">
    <h2 class="font-bold text-gray-900">Shortage by cashier</h2>
    <p class="mt-1 text-xs text-gray-500">Accumulated negative variance for the selected filters.</p>
    <div class="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">
        @forelse($shortageByCashier as $cashierShortage)
            <div class="flex justify-between rounded-xl bg-rose-50 px-3 py-2 text-sm">
                <span class="font-semibold text-gray-800">{{ $cashierShortage->cashier_name }}</span>
                <strong class="text-rose-700">₱{{ number_format((float) $cashierShortage->total_shortage, 2) }}</strong>
            </div>
        @empty
            <p class="text-sm text-gray-500">No cash shortages in this range.</p>
        @endforelse
    </div>
</section>
@endsection
